using System.Collections.Generic;

namespace Decomp.Core.Operators
{
    class CaribbeanVersion : IGameVersion
    {
        public IEnumerable<Operator> GetOperators()
        {
            return new List<Operator>
            {
                new Operator("call_script", 1, Parameter.ScriptIdentifier),
                new Operator("end_try", 3),
                new Operator("try_end", 3),
                new Operator("try_begin", 4),
                new Operator("else_try_begin", 5),
                new Operator("else_try", 5),
                new Operator("try_for_range", 6),
                new Operator("try_for_range_backwards", 7),
                new Operator("try_for_parties", 11),
                new Operator("try_for_agents", 12, Parameter.None, Parameter.Position),
                new Operator("try_for_attached_parties", 15, Parameter.None, Parameter.PartyIdentifier),
                new Operator("try_for_prop_instances", 16, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("store_script_param_1", 21),
                new Operator("store_script_param_2", 22),
                new Operator("store_script_param", 23),
                new Operator("ge", 30),
                new Operator("eq", 31),
                new Operator("gt", 32),
                new Operator("is_between", 33),
                new Operator("entering_town", 36, Parameter.PartyIdentifier),
                new Operator("map_free", 37),
                new Operator("encountered_party_is_attacker", 39),
                new Operator("conversation_screen_is_active", 42),
                new Operator("in_meta_mission", 44),
                new Operator("set_player_troop", 47, Parameter.TroopIdentifier),
                new Operator("store_repeat_object", 50),
                new Operator("is_cheat_mode_enabled", 53),
                new Operator("set_result_string", 60, Parameter.String),
                new Operator("is_camera_in_first_person", 61),
                new Operator("set_camera_in_first_person", 62),
                new Operator("game_key_get_mapped_key_name", 65, Parameter.String, Parameter.GameKeyCode),
                new Operator("key_is_released", 68),
                new Operator("game_key_is_released", 69),
                new Operator("key_is_down", 70, Parameter.KeyCode),
                new Operator("key_clicked", 71, Parameter.KeyCode),
                new Operator("game_key_is_down", 72),
                new Operator("game_key_clicked", 73),
                new Operator("mouse_get_position", 75, Parameter.Position),
                new Operator("omit_key_once", 77, Parameter.KeyCode),
                new Operator("clear_omitted_keys", 78),
                new Operator("get_global_cloud_amount", 90),
                new Operator("set_global_cloud_amount", 91),
                new Operator("get_global_haze_amount", 92),
                new Operator("set_global_haze_amount", 93),
                new Operator("hero_can_join", 101, Parameter.PartyIdentifier),
                new Operator("hero_can_join_as_prisoner", 102, Parameter.PartyIdentifier),
                new Operator("party_can_join", 103),
                new Operator("party_can_join_as_prisoner", 104),
                new Operator("troops_can_join", 105),
                new Operator("troops_can_join_as_prisoner", 106),
                new Operator("party_can_join_party", 107, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_end_battle", 108, Parameter.PartyIdentifier),
                new Operator("main_party_has_troop", 110, Parameter.TroopIdentifier),
                new Operator("party_is_in_town", 130),
                new Operator("party_is_in_any_town", 131, Parameter.PartyIdentifier),
                new Operator("party_is_active", 132, Parameter.PartyIdentifier),
                new Operator("player_has_item", 150, Parameter.ItemIdentifier),
                new Operator("troop_has_item_equipped", 151, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_is_mounted", 152, Parameter.TroopIdentifier),
                new Operator("troop_is_guarantee_ranged", 153, Parameter.TroopIdentifier),
                new Operator("troop_is_guarantee_horse", 154, Parameter.TroopIdentifier),
                new Operator("check_quest_active", 200, Parameter.QuestIdentifier),
                new Operator("check_quest_finished", 201, Parameter.QuestIdentifier),
                new Operator("check_quest_succeeded", 202, Parameter.QuestIdentifier),
                new Operator("check_quest_failed", 203, Parameter.QuestIdentifier),
                new Operator("check_quest_concluded", 204, Parameter.QuestIdentifier),
                new Operator("is_trial_version", 250),
                new Operator("is_edit_mode_enabled", 255),
                new Operator("edit_mode_in_edit_objects_mode", 256),
                new Operator("options_get_damage_to_player", 260),
                new Operator("options_set_damage_to_player", 261),
                new Operator("options_get_damage_to_friends", 262),
                new Operator("options_set_damage_to_friends", 263),
                new Operator("options_get_combat_ai", 264),
                new Operator("options_set_combat_ai", 265),
                new Operator("options_get_campaign_ai", 266),
                new Operator("options_set_campaign_ai", 267),
                new Operator("options_get_combat_speed", 268),
                new Operator("options_set_combat_speed", 269),
                new Operator("options_get_battle_size", 270),
                new Operator("options_set_battle_size", 271),
                new Operator("profile_get_banner_id", 350),
                new Operator("profile_set_banner_id", 351),
                new Operator("get_achievement_stat", 370),
                new Operator("set_achievement_stat", 371),
                new Operator("unlock_achievement", 372),
                new Operator("send_message_to_url", 380, Parameter.String),
                new Operator("multiplayer_send_message_to_server", 388),
                new Operator("multiplayer_send_int_to_server", 389),
                new Operator("multiplayer_send_2_int_to_server", 390),
                new Operator("multiplayer_send_3_int_to_server", 391),
                new Operator("multiplayer_send_4_int_to_server", 392),
                new Operator("multiplayer_send_string_to_server", 393, Parameter.None, Parameter.String),
                new Operator("multiplayer_send_message_to_player", 394),
                new Operator("multiplayer_send_int_to_player", 395),
                new Operator("multiplayer_send_2_int_to_player", 396),
                new Operator("multiplayer_send_3_int_to_player", 397),
                new Operator("multiplayer_send_4_int_to_player", 398),
                new Operator("multiplayer_send_string_to_player", 399, Parameter.None, Parameter.None, Parameter.String),
                new Operator("get_max_players", 400),
                new Operator("player_is_active", 401),
                new Operator("player_get_team_no", 402),
                new Operator("player_set_team_no", 403),
                new Operator("player_get_troop_id", 404),
                new Operator("player_set_troop_id", 405),
                new Operator("player_get_agent_id", 406),
                new Operator("player_get_gold", 407),
                new Operator("player_set_gold", 408),
                new Operator("player_spawn_new_agent", 409),
                new Operator("player_add_spawn_item", 410, Parameter.None, Parameter.InventorySlot, Parameter.ItemIdentifier),
                new Operator("multiplayer_get_my_team", 411),
                new Operator("multiplayer_get_my_troop", 412),
                new Operator("multiplayer_set_my_troop", 413),
                new Operator("multiplayer_get_my_gold", 414),
                new Operator("multiplayer_get_my_player", 415),
                new Operator("multiplayer_clear_scene", 416),
                new Operator("multiplayer_is_server", 417),
                new Operator("multiplayer_is_dedicated_server", 418),
                new Operator("game_in_multiplayer_mode", 419),
                new Operator("multiplayer_make_everyone_enemy", 420),
                new Operator("player_control_agent", 421),
                new Operator("player_get_item_id", 422, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("player_get_banner_id", 423),
                new Operator("game_get_reduce_campaign_ai", 424),
                new Operator("multiplayer_find_spawn_point", 425),
                new Operator("set_spawn_effector_scene_prop_kind", 426),
                new Operator("set_spawn_effector_scene_prop_id", 427),
                new Operator("player_set_is_admin", 429),
                new Operator("player_is_admin", 430),
                new Operator("player_get_score", 431),
                new Operator("player_set_score", 432),
                new Operator("player_get_kill_count", 433),
                new Operator("player_set_kill_count", 434),
                new Operator("player_get_death_count", 435),
                new Operator("player_set_death_count", 436),
                new Operator("player_get_ping", 437),
                new Operator("player_is_busy_with_menus", 438),
                new Operator("player_get_is_muted", 439),
                new Operator("player_set_is_muted", 440),
                new Operator("player_get_unique_id", 441),
                new Operator("player_get_gender", 442),
                new Operator("team_get_bot_kill_count", 450),
                new Operator("team_set_bot_kill_count", 451),
                new Operator("team_get_bot_death_count", 452),
                new Operator("team_set_bot_death_count", 453),
                new Operator("team_get_kill_count", 454),
                new Operator("team_get_score", 455),
                new Operator("team_set_score", 456),
                new Operator("team_set_faction", 457, Parameter.None, Parameter.FactionIdentifier),
                new Operator("team_get_faction", 458),
                new Operator("player_save_picked_up_items_for_next_spawn", 459),
                new Operator("player_get_value_of_original_items", 460),
                new Operator("player_item_slot_is_picked_up", 461, Parameter.None, Parameter.InventorySlot),
                new Operator("kick_player", 465),
                new Operator("ban_player", 466),
                new Operator("save_ban_info_of_player", 467),
                new Operator("ban_player_using_saved_ban_info", 468),
                new Operator("start_multiplayer_mission", 470, Parameter.MissionTemplateIdentifier, Parameter.SceneIdentifier),
                new Operator("server_add_message_to_log", 473, Parameter.String),
                new Operator("server_get_renaming_server_allowed", 475),
                new Operator("server_get_changing_game_type_allowed", 476),
                new Operator("server_get_combat_speed", 478),
                new Operator("server_set_combat_speed", 479),
                new Operator("server_get_friendly_fire", 480),
                new Operator("server_set_friendly_fire", 481),
                new Operator("server_get_control_block_dir", 482),
                new Operator("server_set_control_block_dir", 483),
                new Operator("server_set_password", 484, Parameter.String),
                new Operator("server_get_add_to_game_servers_list", 485),
                new Operator("server_set_add_to_game_servers_list", 486),
                new Operator("server_get_ghost_mode", 487),
                new Operator("server_set_ghost_mode", 488),
                new Operator("server_set_name", 489, Parameter.String),
                new Operator("server_get_max_num_players", 490),
                new Operator("server_set_max_num_players", 491),
                new Operator("server_set_welcome_message", 492, Parameter.String),
                new Operator("server_get_melee_friendly_fire", 493),
                new Operator("server_set_melee_friendly_fire", 494),
                new Operator("server_get_friendly_fire_damage_self_ratio", 495),
                new Operator("server_set_friendly_fire_damage_self_ratio", 496),
                new Operator("server_get_friendly_fire_damage_friend_ratio", 497),
                new Operator("server_set_friendly_fire_damage_friend_ratio", 498),
                new Operator("server_get_anti_cheat", 499),
                new Operator("server_set_anti_cheat", 477),
                new Operator("troop_set_slot", 500, Parameter.TroopIdentifier),
                new Operator("party_set_slot", 501, Parameter.PartyIdentifier),
                new Operator("faction_set_slot", 502, Parameter.FactionIdentifier),
                new Operator("scene_set_slot", 503, Parameter.SceneIdentifier),
                new Operator("party_template_set_slot", 504, Parameter.PartyTemplateIdentifier),
                new Operator("agent_set_slot", 505),
                new Operator("quest_set_slot", 506, Parameter.QuestIdentifier),
                new Operator("item_set_slot", 507, Parameter.ItemIdentifier),
                new Operator("player_set_slot", 508),
                new Operator("team_set_slot", 509),
                new Operator("scene_prop_set_slot", 510, Parameter.ScenePropIdentifier),
                new Operator("troop_get_slot", 520, Parameter.None, Parameter.TroopIdentifier),
                new Operator("party_get_slot", 521, Parameter.None, Parameter.PartyIdentifier),
                new Operator("faction_get_slot", 522, Parameter.None, Parameter.FactionIdentifier),
                new Operator("scene_get_slot", 523, Parameter.None, Parameter.SceneIdentifier),
                new Operator("party_template_get_slot", 524, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("agent_get_slot", 525),
                new Operator("quest_get_slot", 526, Parameter.None, Parameter.QuestIdentifier),
                new Operator("item_get_slot", 527, Parameter.None, Parameter.ItemIdentifier),
                new Operator("player_get_slot", 528),
                new Operator("team_get_slot", 529),
                new Operator("scene_prop_get_slot", 530, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("troop_slot_eq", 540, Parameter.TroopIdentifier),
                new Operator("party_slot_eq", 541, Parameter.PartyIdentifier),
                new Operator("faction_slot_eq", 542, Parameter.FactionIdentifier),
                new Operator("scene_slot_eq", 543, Parameter.SceneIdentifier),
                new Operator("party_template_slot_eq", 544, Parameter.PartyTemplateIdentifier),
                new Operator("agent_slot_eq", 545),
                new Operator("quest_slot_eq", 546, Parameter.QuestIdentifier),
                new Operator("item_slot_eq", 547, Parameter.ItemIdentifier),
                new Operator("player_slot_eq", 548),
                new Operator("team_slot_eq", 549),
                new Operator("scene_prop_slot_eq", 550, Parameter.ScenePropIdentifier),
                new Operator("troop_slot_ge", 560, Parameter.TroopIdentifier),
                new Operator("party_slot_ge", 561, Parameter.PartyIdentifier),
                new Operator("faction_slot_ge", 562, Parameter.FactionIdentifier),
                new Operator("scene_slot_ge", 563, Parameter.SceneIdentifier),
                new Operator("party_template_slot_ge", 564, Parameter.PartyTemplateIdentifier),
                new Operator("agent_slot_ge", 565),
                new Operator("quest_slot_ge", 566, Parameter.QuestIdentifier),
                new Operator("item_slot_ge", 567, Parameter.ItemIdentifier),
                new Operator("player_slot_ge", 568),
                new Operator("team_slot_ge", 569),
                new Operator("scene_prop_slot_ge", 570, Parameter.ScenePropIdentifier),
                new Operator("play_sound_at_position", 599, Parameter.SoundIdentifier, Parameter.Position),
                new Operator("play_sound", 600, Parameter.SoundIdentifier),
                new Operator("play_track", 601, Parameter.TrackIdentifier),
                new Operator("play_cue_track", 602, Parameter.TrackIdentifier),
                new Operator("music_set_situation", 603, Parameter.MusicFlags),
                new Operator("music_set_culture", 604, Parameter.MusicFlags),
                new Operator("stop_all_sounds", 609),
                new Operator("store_last_sound_channel", 615),
                new Operator("stop_sound_channel", 616),
                new Operator("copy_position", 700),
                new Operator("init_position", 701, Parameter.Position),
                new Operator("get_trigger_object_position", 702, Parameter.Position),
                new Operator("get_angle_between_positions", 705, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("position_has_line_of_sight_to_position", 707, Parameter.Position, Parameter.Position),
                new Operator("get_distance_between_positions", 710, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("get_distance_between_positions_in_meters", 711, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("get_sq_distance_between_positions", 712, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("get_sq_distance_between_positions_in_meters", 713, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("position_is_behind_position", 714, Parameter.Position, Parameter.Position),
                new Operator("get_sq_distance_between_position_heights", 715, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("position_transform_position_to_parent", 716, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_transform_position_to_local", 717, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_copy_rotation", 718, Parameter.Position, Parameter.Position),
                new Operator("position_copy_origin", 719, Parameter.Position, Parameter.Position),
                new Operator("position_move_x", 720),
                new Operator("position_move_y", 721, Parameter.Position),
                new Operator("position_move_z", 722, Parameter.Position),
                new Operator("position_rotate_x", 723, Parameter.Position),
                new Operator("position_rotate_y", 724, Parameter.Position),
                new Operator("position_rotate_z", 725, Parameter.Position),
                new Operator("position_get_x", 726, Parameter.None, Parameter.Position),
                new Operator("position_get_y", 727, Parameter.None, Parameter.Position),
                new Operator("position_get_z", 728, Parameter.None, Parameter.Position),
                new Operator("position_set_x", 729, Parameter.Position),
                new Operator("position_set_y", 730, Parameter.Position),
                new Operator("position_set_z", 731, Parameter.Position),
                new Operator("position_rotate_z_floating", 734, Parameter.Position),
                new Operator("position_get_scale_x", 735, Parameter.None, Parameter.Position),
                new Operator("position_get_scale_y", 736, Parameter.None, Parameter.Position),
                new Operator("position_get_scale_z", 737, Parameter.None, Parameter.Position),
                new Operator("position_rotate_x_floating", 738, Parameter.Position),
                new Operator("position_rotate_y_floating", 739, Parameter.Position),
                new Operator("position_get_rotation_around_z", 740, Parameter.None, Parameter.Position),
                new Operator("position_normalize_origin", 741, Parameter.None, Parameter.Position),
                new Operator("position_get_rotation_around_x", 742, Parameter.None, Parameter.Position),
                new Operator("position_get_rotation_around_y", 743, Parameter.None, Parameter.Position),
                new Operator("position_set_scale_x", 744, Parameter.Position),
                new Operator("position_set_scale_y", 745, Parameter.Position),
                new Operator("position_set_scale_z", 746, Parameter.Position),
                new Operator("position_get_screen_projection", 750, Parameter.Position, Parameter.Position),
                new Operator("mouse_get_world_projection", 751, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_set_z_to_ground_level", 791, Parameter.Position),
                new Operator("position_get_distance_to_terrain", 792, Parameter.None, Parameter.Position),
                new Operator("position_get_distance_to_ground_level", 793, Parameter.None, Parameter.Position),
                new Operator("position_get_length", 800, Parameter.None, Parameter.Position),
                new Operator("get_dot_product_of_positions", 801, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("get_cross_product_of_positions", 802, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("start_presentation", 900, Parameter.PresentationIdentifier),
                new Operator("start_background_presentation", 901, Parameter.PresentationIdentifier),
                new Operator("presentation_set_duration", 902),
                new Operator("is_presentation_active", 903, Parameter.PresentationIdentifier),
                new Operator("create_text_overlay", 910, Parameter.None, Parameter.String),
                new Operator("create_mesh_overlay", 911, Parameter.None, Parameter.MeshIdentifier),
                new Operator("create_button_overlay", 912, Parameter.None, Parameter.String),
                new Operator("create_image_button_overlay", 913, Parameter.None, Parameter.MeshIdentifier, Parameter.MeshIdentifier),
                new Operator("create_slider_overlay", 914),
                new Operator("create_progress_overlay", 915),
                new Operator("create_combo_button_overlay", 916),
                new Operator("create_text_box_overlay", 917),
                new Operator("create_check_box_overlay", 918),
                new Operator("create_simple_text_box_overlay", 919),
                new Operator("overlay_set_text", 920, Parameter.None, Parameter.String),
                new Operator("overlay_set_color", 921),
                new Operator("overlay_set_alpha", 922, Parameter.None, Parameter.Alpha),
                new Operator("overlay_set_hilight_color", 923),
                new Operator("overlay_set_hilight_alpha", 924, Parameter.None, Parameter.Alpha),
                new Operator("overlay_set_size", 925, Parameter.None, Parameter.Position),
                new Operator("overlay_set_position", 926, Parameter.None, Parameter.Position),
                new Operator("overlay_set_val", 927),
                new Operator("overlay_set_boundaries", 928),
                new Operator("overlay_set_area_size", 929, Parameter.None, Parameter.Position),
                new Operator("overlay_set_mesh_rotation", 930, Parameter.None, Parameter.Position),
                new Operator("overlay_add_item", 931, Parameter.None, Parameter.String),
                new Operator("overlay_animate_to_color", 932),
                new Operator("overlay_animate_to_alpha", 933),
                new Operator("overlay_animate_to_highlight_color", 934),
                new Operator("overlay_animate_to_highlight_alpha", 935),
                new Operator("overlay_animate_to_size", 936, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("overlay_animate_to_position", 937, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("create_image_button_overlay_with_tableau_material", 938, Parameter.None, Parameter.MeshIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("create_mesh_overlay_with_tableau_material", 939, Parameter.None, Parameter.MeshIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("create_game_button_overlay", 940, Parameter.None, Parameter.String),
                new Operator("create_in_game_button_overlay", 941, Parameter.None, Parameter.String),
                new Operator("create_number_box_overlay", 942),
                new Operator("create_listbox_overlay", 943),
                new Operator("create_mesh_overlay_with_item_id", 944, Parameter.None, Parameter.ItemIdentifier),
                new Operator("set_container_overlay", 945),
                new Operator("overlay_get_position", 946),
                new Operator("overlay_set_display", 947),
                new Operator("create_combo_label_overlay", 948),
                new Operator("overlay_obtain_focus", 949),
                new Operator("overlay_set_tooltip", 950, Parameter.None, Parameter.String),
                new Operator("overlay_set_container_overlay", 951),
                new Operator("overlay_set_additional_render_height", 952),
                new Operator("overlay_button_set_type", 953),
                new Operator("overlay_get_scroll_pos", 954),
                new Operator("overlay_set_scroll_pos", 955),
                new Operator("overlay_set_material", 956, Parameter.None, Parameter.String),
                new Operator("show_object_details_overlay", 960),
                new Operator("show_item_details", 970, Parameter.ItemIdentifier, Parameter.Position),
                new Operator("close_item_details", 971),
                new Operator("show_item_details_with_modifier", 972, Parameter.ItemIdentifier, Parameter.ItemModifier, Parameter.Position),
                new Operator("context_menu_add_item", 980, Parameter.String),
                new Operator("get_average_game_difficulty", 990),
                new Operator("get_level_boundary", 991),
                new Operator("all_enemies_defeated", 1003),
                new Operator("race_completed_by_player", 1004),
                new Operator("num_active_teams_le", 1005),
                new Operator("main_hero_fallen", 1006),
                new Operator("finish_party_battle_mode", 1019),
                new Operator("set_party_battle_mode", 1020),
                new Operator("set_camera_follow_party", 1021, Parameter.PartyIdentifier),
                new Operator("start_map_conversation", 1025, Parameter.TroopIdentifier),
                new Operator("rest_for_hours", 1030),
                new Operator("rest_for_hours_interactive", 1031),
                new Operator("add_xp_to_troop", 1062, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_gold_as_xp", 1063, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_xp_as_reward", 1064),
                new Operator("add_gold_to_party", 1070),
                new Operator("set_party_creation_random_limits", 1080),
                new Operator("troop_set_note_available", 1095, Parameter.TroopIdentifier),
                new Operator("faction_set_note_available", 1096, Parameter.FactionIdentifier),
                new Operator("party_set_note_available", 1097, Parameter.PartyIdentifier),
                new Operator("quest_set_note_available", 1098, Parameter.QuestIdentifier),
                new Operator("spawn_around_party", 1100),
                new Operator("set_spawn_radius", 1103),
                new Operator("display_debug_message", 1104, Parameter.String, Parameter.Color),
                new Operator("display_log_message", 1105, Parameter.String, Parameter.Color),
                new Operator("display_message", 1106, Parameter.String, Parameter.Color),
                new Operator("set_show_messages", 1107),
                new Operator("add_troop_note_tableau_mesh", 1108, Parameter.TroopIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_faction_note_tableau_mesh", 1109, Parameter.FactionIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_party_note_tableau_mesh", 1110, Parameter.PartyIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_quest_note_tableau_mesh", 1111, Parameter.QuestIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_info_page_note_tableau_mesh", 1090, Parameter.InfoPageIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_troop_note_from_dialog", 1114, Parameter.TroopIdentifier),
                new Operator("add_faction_note_from_dialog", 1115, Parameter.FactionIdentifier),
                new Operator("add_party_note_from_dialog", 1116, Parameter.PartyIdentifier),
                new Operator("add_quest_note_from_dialog", 1112, Parameter.QuestIdentifier),
                new Operator("add_info_page_note_from_dialog", 1091, Parameter.InfoPageIdentifier),
                new Operator("add_troop_note_from_sreg", 1117, Parameter.TroopIdentifier, Parameter.None, Parameter.String),
                new Operator("add_faction_note_from_sreg", 1118, Parameter.FactionIdentifier, Parameter.None, Parameter.String),
                new Operator("add_party_note_from_sreg", 1119, Parameter.PartyIdentifier, Parameter.None, Parameter.String),
                new Operator("add_quest_note_from_sreg", 1113, Parameter.QuestIdentifier, Parameter.None, Parameter.String),
                new Operator("add_info_page_note_from_sreg", 1092, Parameter.InfoPageIdentifier, Parameter.None, Parameter.String),
                new Operator("tutorial_box", 1120, Parameter.String, Parameter.String),
                new Operator("dialog_box", 1120, Parameter.String, Parameter.String),
                new Operator("question_box", 1121, Parameter.String, Parameter.String, Parameter.String),
                new Operator("tutorial_message", 1122, Parameter.String),
                new Operator("tutorial_message_set_position", 1123, Parameter.Position, Parameter.Position),
                new Operator("tutorial_message_set_size", 1124),
                new Operator("tutorial_message_set_center_justify", 1125),
                new Operator("tutorial_message_set_background", 1126),
                new Operator("set_tooltip_text", 1130, Parameter.String),
                new Operator("reset_price_rates", 1170),
                new Operator("set_price_rate_for_item", 1171, Parameter.ItemIdentifier),
                new Operator("set_price_rate_for_item_type", 1172, Parameter.ItemType),
                new Operator("party_join", 1201),
                new Operator("party_join_as_prisoner", 1202),
                new Operator("troop_join", 1203, Parameter.TroopIdentifier),
                new Operator("troop_join_as_prisoner", 1204, Parameter.TroopIdentifier),
                new Operator("remove_member_from_party", 1210, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("remove_regular_prisoners", 1211, Parameter.PartyIdentifier),
                new Operator("remove_troops_from_companions", 1215, Parameter.TroopIdentifier),
                new Operator("remove_troops_from_prisoners", 1216, Parameter.TroopIdentifier),
                new Operator("heal_party", 1225, Parameter.PartyIdentifier),
                new Operator("disable_party", 1230, Parameter.PartyIdentifier),
                new Operator("enable_party", 1231, Parameter.PartyIdentifier),
                new Operator("remove_party", 1232, Parameter.PartyIdentifier),
                new Operator("add_companion_party", 1233),
                new Operator("add_troop_to_site", 1250, Parameter.TroopIdentifier, Parameter.SceneIdentifier),
                new Operator("remove_troop_from_site", 1251, Parameter.TroopIdentifier, Parameter.SceneIdentifier),
                new Operator("modify_visitors_at_site", 1261, Parameter.SceneIdentifier),
                new Operator("reset_visitors", 1262),
                new Operator("set_visitor", 1263, Parameter.None, Parameter.TroopIdentifier),
                new Operator("set_visitors", 1264, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_visitors_to_current_scene", 1265, Parameter.None, Parameter.TroopIdentifier),
                new Operator("scene_set_day_time", 1266),
                new Operator("set_relation", 1270, Parameter.FactionIdentifier, Parameter.FactionIdentifier),
                new Operator("faction_set_name", 1275, Parameter.FactionIdentifier, Parameter.String),
                new Operator("faction_set_color", 1276, Parameter.FactionIdentifier),
                new Operator("faction_get_color", 1277, Parameter.None, Parameter.FactionIdentifier),
                new Operator("start_quest", 1280, Parameter.QuestIdentifier),
                new Operator("complete_quest", 1281, Parameter.QuestIdentifier),
                new Operator("succeed_quest", 1282, Parameter.QuestIdentifier),
                new Operator("fail_quest", 1283, Parameter.QuestIdentifier),
                new Operator("cancel_quest", 1284, Parameter.QuestIdentifier),
                new Operator("set_quest_progression", 1285, Parameter.QuestIdentifier),
                new Operator("conclude_quest", 1286, Parameter.QuestIdentifier),
                new Operator("setup_quest_text", 1290, Parameter.QuestIdentifier),
                new Operator("setup_quest_giver", 1291, Parameter.QuestIdentifier, Parameter.String),
                new Operator("start_encounter", 1300, Parameter.PartyIdentifier),
                new Operator("leave_encounter", 1301),
                new Operator("encounter_attack", 1302),
                new Operator("select_enemy", 1303),
                new Operator("set_passage_menu", 1304),
                new Operator("auto_set_meta_mission_at_end_commited", 1305),
                new Operator("end_current_battle", 1307),
                new Operator("set_mercenary_source_party", 1320),
                new Operator("set_merchandise_modifier_quality", 1490),
                new Operator("set_merchandise_max_value", 1491),
                new Operator("reset_item_probabilities", 1492),
                new Operator("set_item_probability_in_merchandise", 1493, Parameter.ItemIdentifier),
                new Operator("troop_set_name", 1501, Parameter.TroopIdentifier, Parameter.String),
                new Operator("troop_set_plural_name", 1502, Parameter.TroopIdentifier, Parameter.String),
                new Operator("troop_set_face_key_from_current_profile", 1503, Parameter.TroopIdentifier),
                new Operator("troop_set_type", 1505, Parameter.TroopIdentifier),
                new Operator("troop_get_type", 1506, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_is_hero", 1507, Parameter.TroopIdentifier),
                new Operator("troop_is_wounded", 1508, Parameter.TroopIdentifier),
                new Operator("troop_set_auto_equip", 1509, Parameter.TroopIdentifier),
                new Operator("troop_ensure_inventory_space", 1510, Parameter.TroopIdentifier),
                new Operator("troop_sort_inventory", 1511, Parameter.TroopIdentifier),
                new Operator("troop_add_merchandise", 1512, Parameter.TroopIdentifier, Parameter.ItemType),
                new Operator("troop_add_merchandise_with_faction", 1513, Parameter.TroopIdentifier, Parameter.FactionIdentifier, Parameter.ItemType),
                new Operator("troop_get_xp", 1515, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_get_class", 1516, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_class", 1517, Parameter.TroopIdentifier),
                new Operator("troop_raise_attribute", 1520, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("troop_raise_skill", 1521, Parameter.TroopIdentifier, Parameter.SkillIdentifier),
                new Operator("troop_raise_proficiency", 1522, Parameter.TroopIdentifier, Parameter.WeaponProficiency),
                new Operator("troop_raise_proficiency_linear", 1523),
                new Operator("troop_add_proficiency_points", 1525, Parameter.TroopIdentifier),
                new Operator("troop_add_gold", 1528, Parameter.TroopIdentifier),
                new Operator("troop_remove_gold", 1529, Parameter.TroopIdentifier),
                new Operator("troop_add_item", 1530, Parameter.TroopIdentifier, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("troop_remove_item", 1531, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_clear_inventory", 1532, Parameter.TroopIdentifier),
                new Operator("troop_equip_items", 1533, Parameter.TroopIdentifier),
                new Operator("troop_inventory_slot_set_item_amount", 1534, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_inventory_slot_get_item_amount", 1537, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_inventory_slot_get_item_max_amount", 1538, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_add_items", 1535, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_remove_items", 1536),
                new Operator("troop_loot_troop", 1539, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_get_inventory_capacity", 1540, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_get_inventory_slot", 1541, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_get_inventory_slot_modifier", 1542, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_inventory_slot", 1543, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_inventory_slot_modifier", 1544, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_faction", 1550, Parameter.TroopIdentifier, Parameter.FactionIdentifier),
                new Operator("troop_set_age", 1555, Parameter.TroopIdentifier),
                new Operator("troop_set_health", 1560, Parameter.TroopIdentifier),
                new Operator("troop_get_upgrade_troop", 1561, Parameter.None, Parameter.TroopIdentifier),
                new Operator("item_get_type", 1570, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_missile_speed", 1580, Parameter.None, Parameter.ItemIdentifier),
                new Operator("troop_get_ranged_damage_adder", 1579, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_ranged_damage_adder", 1580, Parameter.TroopIdentifier),
                new Operator("troop_get_blunt_damage_adder", 1581, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_blunt_damage_adder", 1582, Parameter.TroopIdentifier),
                new Operator("troop_get_pierce_damage_adder", 1583, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_pierce_damage_adder", 1584, Parameter.TroopIdentifier),
                new Operator("troop_get_cut_damage_adder", 1585, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_cut_damage_adder", 1586, Parameter.TroopIdentifier),
                new Operator("troop_get_melee_speed_adder", 1587, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_melee_speed_adder", 1588, Parameter.TroopIdentifier),
                new Operator("troop_get_ranged_speed_adder", 1589, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_ranged_speed_adder", 1590, Parameter.TroopIdentifier),
                new Operator("troop_get_accuracy_adder", 1591, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_accuracy_adder", 1592, Parameter.TroopIdentifier),
                new Operator("troop_get_charge_adder", 1593, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_charge_adder", 1594, Parameter.TroopIdentifier),
                new Operator("troop_get_horse_speed_adder", 1595, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_horse_speed_adder", 1596, Parameter.TroopIdentifier),
                new Operator("troop_get_riding_limit_adder", 1597, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_riding_limit_adder", 1598, Parameter.TroopIdentifier),
                new Operator("troop_get_strength_limit_adder", 1599, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_strength_limit_adder", 1600, Parameter.TroopIdentifier),
                new Operator("party_get_num_companions", 1601, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_prisoners", 1602, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_flags", 1603, Parameter.PartyIdentifier),
                new Operator("party_set_marshall", 1604, Parameter.PartyIdentifier),
                new Operator("party_set_extra_text", 1605, Parameter.PartyIdentifier, Parameter.String),
                new Operator("party_set_aggressiveness", 1606, Parameter.PartyIdentifier),
                new Operator("party_set_courage", 1607, Parameter.PartyIdentifier),
                new Operator("party_get_current_terrain", 1608, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_template_id", 1609, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_add_members", 1610, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_add_prisoners", 1611, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_add_leader", 1612, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_force_add_members", 1613, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_force_add_prisoners", 1614, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_remove_members", 1615),
                new Operator("party_remove_prisoners", 1616),
                new Operator("party_clear", 1617, Parameter.PartyIdentifier),
                new Operator("party_wound_members", 1618, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_remove_members_wounded_first", 1619),
                new Operator("party_set_faction", 1620, Parameter.PartyIdentifier, Parameter.FactionIdentifier),
                new Operator("party_relocate_near_party", 1623, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_get_position", 1625, Parameter.Position, Parameter.PartyIdentifier),
                new Operator("party_set_position", 1626, Parameter.PartyIdentifier, Parameter.Position),
                new Operator("map_get_random_position_around_position", 1627, Parameter.Position, Parameter.Position),
                new Operator("map_get_land_position_around_position", 1628, Parameter.Position, Parameter.Position),
                new Operator("map_get_water_position_around_position", 1629, Parameter.Position, Parameter.Position),
                new Operator("party_count_members_of_type", 1630, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_count_companions_of_type", 1631, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_count_prisoners_of_type", 1632, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_get_free_companions_capacity", 1633, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_free_prisoners_capacity", 1634, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_base_terrain_strength", 1635, Parameter.PartyIdentifier),
                new Operator("party_get_ai_initiative", 1638, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_ai_initiative", 1639, Parameter.PartyIdentifier),
                new Operator("party_set_ai_behavior", 1640, Parameter.PartyIdentifier, Parameter.AiBehavior),
                new Operator("party_set_ai_object", 1641, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_set_ai_target_position", 1642, Parameter.PartyIdentifier, Parameter.Position),
                new Operator("party_set_ai_patrol_radius", 1643, Parameter.PartyIdentifier),
                new Operator("party_ignore_player", 1644, Parameter.PartyIdentifier),
                new Operator("party_set_bandit_attraction", 1645, Parameter.PartyIdentifier),
                new Operator("party_get_helpfulness", 1646, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_helpfulness", 1647, Parameter.PartyIdentifier),
                new Operator("party_set_ignore_with_player_party", 1648, Parameter.PartyIdentifier),
                new Operator("party_get_ignore_with_player_party", 1649, Parameter.PartyIdentifier),
                new Operator("party_get_num_companion_stacks", 1650, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_prisoner_stacks", 1651, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_troop_id", 1652, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_size", 1653, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_num_wounded", 1654, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_troop_dna", 1655, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_troop_id", 1656, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_size", 1657, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_troop_dna", 1658, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_experience", 1659, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_attach_to_party", 1660, Parameter.PartyIdentifier),
                new Operator("party_detach", 1661, Parameter.PartyIdentifier),
                new Operator("party_collect_attachments_to_party", 1662, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_quick_attach_to_current_battle", 1663, Parameter.PartyIdentifier),
                new Operator("party_stack_get_num_upgradeable", 1664, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_cur_town", 1665, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_leave_cur_battle", 1666, Parameter.PartyIdentifier),
                new Operator("party_set_next_battle_simulation_time", 1667, Parameter.PartyIdentifier),
                new Operator("party_stack_upgrade", 1668, Parameter.PartyIdentifier),
                new Operator("party_set_name", 1669, Parameter.PartyIdentifier, Parameter.String),
                new Operator("party_add_xp_to_stack", 1670, Parameter.PartyIdentifier),
                new Operator("party_get_morale", 1671, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_morale", 1672, Parameter.PartyIdentifier),
                new Operator("party_upgrade_with_xp", 1673, Parameter.PartyIdentifier),
                new Operator("party_add_xp", 1674, Parameter.PartyIdentifier),
                new Operator("party_add_template", 1675, Parameter.PartyIdentifier, Parameter.PartyTemplateIdentifier),
                new Operator("party_set_icon", 1676, Parameter.PartyIdentifier, Parameter.MapIconIdentifier),
                new Operator("party_set_banner_icon", 1677, Parameter.PartyIdentifier, Parameter.MapIconIdentifier),
                new Operator("party_add_particle_system", 1678, Parameter.PartyIdentifier, Parameter.ParticleSystemIdentifier),
                new Operator("party_clear_particle_systems", 1679, Parameter.PartyIdentifier),
                new Operator("party_get_battle_opponent", 1680, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_icon", 1681, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_extra_icon", 1682, Parameter.PartyIdentifier, Parameter.MapIconIdentifier),
                new Operator("party_get_skill_level", 1685, Parameter.None, Parameter.PartyIdentifier, Parameter.SkillIdentifier),
                new Operator("agent_get_speed", 1689, Parameter.Position),
                new Operator("get_battle_advantage", 1690),
                new Operator("set_battle_advantage", 1691),
                new Operator("agent_refill_wielded_shield_hit_points", 1692),
                new Operator("agent_is_in_special_mode", 1693),
                new Operator("party_get_attached_to", 1694, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_attached_parties", 1695, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_attached_party_with_rank", 1696, Parameter.None, Parameter.PartyIdentifier),
                new Operator("inflict_casualties_to_party_group", 1697, Parameter.PartyIdentifier, Parameter.None, Parameter.PartyIdentifier),
                new Operator("distribute_party_among_party_group", 1698, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("agent_is_routed", 1699),
                new Operator("get_player_agent_no", 1700),
                new Operator("get_player_agent_kill_count", 1701),
                new Operator("agent_is_alive", 1702),
                new Operator("agent_is_wounded", 1703),
                new Operator("agent_is_human", 1704),
                new Operator("get_player_agent_own_troop_kill_count", 1705),
                new Operator("agent_is_ally", 1706),
                new Operator("agent_is_non_player", 1707),
                new Operator("agent_is_defender", 1708),
                new Operator("agent_is_active", 1712),
                new Operator("agent_get_look_position", 1709, Parameter.Position),
                new Operator("agent_get_position", 1710, Parameter.Position),
                new Operator("agent_set_position", 1711, Parameter.None, Parameter.Position),
                new Operator("agent_set_look_target_agent", 1713),
                new Operator("agent_get_horse", 1714),
                new Operator("agent_get_rider", 1715),
                new Operator("agent_get_party_id", 1716),
                new Operator("agent_get_entry_no", 1717),
                new Operator("agent_get_troop_id", 1718),
                new Operator("agent_get_item_id", 1719),
                new Operator("store_agent_hit_points", 1720),
                new Operator("agent_set_hit_points", 1721),
                new Operator("agent_deliver_damage_to_agent", 1722, Parameter.None, Parameter.None, Parameter.None, Parameter.ItemIdentifier),
                new Operator("agent_get_kill_count", 1723),
                new Operator("agent_get_player_id", 1724),
                new Operator("agent_set_invulnerable_shield", 1725),
                new Operator("agent_get_wielded_item", 1726),
                new Operator("agent_get_ammo", 1727),
                new Operator("agent_refill_ammo", 1728),
                new Operator("agent_has_item_equipped", 1729, Parameter.None, Parameter.ItemIdentifier),
                new Operator("agent_set_scripted_destination", 1730, Parameter.None, Parameter.Position),
                new Operator("agent_get_scripted_destination", 1731, Parameter.Position),
                new Operator("agent_force_rethink", 1732),
                new Operator("agent_set_no_death_knock_down_only", 1733),
                new Operator("agent_set_horse_speed_factor", 1734),
                new Operator("agent_clear_scripted_mode", 1735),
                new Operator("agent_set_speed_limit", 1736),
                new Operator("agent_ai_set_always_attack_in_melee", 1737),
                new Operator("agent_get_simple_behavior", 1738),
                new Operator("agent_get_combat_state", 1739),
                new Operator("agent_set_animation", 1740, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_stand_animation", 1741, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_walk_forward_animation", 1742, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_animation_progress", 1743),
                new Operator("agent_set_look_target_position", 1744, Parameter.None, Parameter.Position),
                new Operator("agent_set_attack_action", 1745),
                new Operator("agent_set_defend_action", 1746),
                new Operator("agent_set_wielded_item", 1747, Parameter.None, Parameter.ItemIdentifier),
                new Operator("agent_set_scripted_destination_no_attack", 1748, Parameter.None, Parameter.Position),
                new Operator("agent_fade_out", 1749),
                new Operator("agent_play_sound", 1750, Parameter.None, Parameter.SoundIdentifier),
                new Operator("agent_start_running_away", 1751, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("agent_stop_running_away", 1752),
                new Operator("agent_ai_set_aggressiveness", 1753),
                new Operator("agent_set_kick_allowed", 1754),
                new Operator("remove_agent", 1755),
                new Operator("agent_get_attached_scene_prop", 1756),
                new Operator("agent_set_attached_scene_prop", 1757, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("agent_set_attached_scene_prop_x", 1758),
                new Operator("agent_set_attached_scene_prop_z", 1759),
                new Operator("agent_get_time_elapsed_since_removed", 1760),
                new Operator("agent_get_number_of_enemies_following", 1761),
                new Operator("agent_set_no_dynamics", 1762),
                new Operator("agent_get_attack_action", 1763),
                new Operator("agent_get_defend_action", 1764),
                new Operator("agent_get_group", 1765),
                new Operator("agent_set_group", 1766),
                new Operator("agent_get_action_dir", 1767),
                new Operator("agent_get_animation", 1768),
                new Operator("agent_is_in_parried_animation", 1769),
                new Operator("agent_get_team", 1770),
                new Operator("agent_set_team", 1771),
                new Operator("agent_get_class", 1772),
                new Operator("agent_get_division", 1773),
                new Operator("agent_unequip_item", 1774, Parameter.None, Parameter.ItemIdentifier),
                new Operator("class_is_listening_order", 1775),
                new Operator("agent_set_ammo", 1776, Parameter.None, Parameter.ItemIdentifier),
                new Operator("agent_add_offer_with_timeout", 1777),
                new Operator("agent_check_offer_from_agent", 1778),
                new Operator("agent_equip_item", 1779, Parameter.None, Parameter.ItemIdentifier),
                new Operator("entry_point_get_position", 1780, Parameter.Position),
                new Operator("entry_point_set_position", 1781, Parameter.None, Parameter.Position),
                new Operator("entry_point_is_auto_generated", 1782),
                new Operator("agent_set_division", 1783),
                new Operator("team_get_hold_fire_order", 1784),
                new Operator("team_get_movement_order", 1785),
                new Operator("team_get_riding_order", 1786),
                new Operator("team_get_weapon_usage_order", 1787),
                new Operator("teams_are_enemies", 1788),
                new Operator("close_order_menu", 1789),
                new Operator("team_give_order", 1790),
                new Operator("team_set_order_position", 1791, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("team_get_leader", 1792),
                new Operator("team_set_leader", 1793),
                new Operator("team_get_order_position", 1794, Parameter.Position),
                new Operator("team_set_order_listener", 1795),
                new Operator("team_set_relation", 1796),
                new Operator("set_rain", 1797),
                new Operator("set_fog_distance", 1798, Parameter.None, Parameter.Color),
                new Operator("get_scene_boundaries", 1799, Parameter.Position, Parameter.Position),
                new Operator("scene_prop_enable_after_time", 1800, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_has_agent_on_it", 1801, Parameter.ScenePropIdentifier),
                new Operator("agent_clear_relations_with_agents", 1802),
                new Operator("agent_add_relation_with_agent", 1803),
                new Operator("agent_get_item_slot", 1804),
                new Operator("ai_mesh_face_group_show_hide", 1805),
                new Operator("agent_is_alarmed", 1806),
                new Operator("agent_set_is_alarmed", 1807),
                new Operator("agent_stop_sound", 1808),
                new Operator("agent_set_attached_scene_prop_y", 1809),
                new Operator("scene_prop_get_num_instances", 1810, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_instance", 1811, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_visibility", 1812, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_set_visibility", 1813, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_set_hit_points", 1814, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_hit_points", 1815, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_max_hit_points", 1816, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_team", 1817, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_set_team", 1818, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_set_prune_time", 1819, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_set_cur_hit_points", 1820, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_fade_out", 1822, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_fade_in", 1823, Parameter.ScenePropIdentifier),
                new Operator("agent_get_ammo_for_slot", 1825),
                new Operator("agent_is_in_line_of_sight", 1826, Parameter.None, Parameter.Position),
                new Operator("agent_deliver_damage_to_agent_advanced", 1827, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.ItemIdentifier),
                new Operator("team_get_gap_distance", 1828),
                new Operator("add_missile", 1829, Parameter.None, Parameter.Position, Parameter.None, Parameter.ItemIdentifier, Parameter.ItemModifier, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("scene_item_get_num_instances", 1830, Parameter.None, Parameter.ItemIdentifier),
                new Operator("scene_item_get_instance", 1831, Parameter.None, Parameter.ItemIdentifier),
                new Operator("scene_spawned_item_get_num_instances", 1832, Parameter.None, Parameter.ItemIdentifier),
                new Operator("scene_spawned_item_get_instance", 1833, Parameter.None, Parameter.ItemIdentifier),
                new Operator("scene_allows_mounted_units", 1834),
                new Operator("class_set_name", 1837, Parameter.None, Parameter.String),
                new Operator("prop_instance_is_valid", 1838, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_variation_id", 1840, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_variation_id_2", 1841, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_position", 1850, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_starting_position", 1851, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_scale", 1852, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_scene_prop_kind", 1853, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_scale", 1854, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_position", 1855, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("prop_instance_get_parent_instance", 1856, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_parent_instance", 1857, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_local_position", 1858, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_local_position", 1859, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("prop_instance_animate_to_position", 1860, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("prop_instance_stop_animating", 1861, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_is_animating", 1862, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_animation_target_position", 1863, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_enable_physics", 1864, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_rotate_to_position", 1865, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("prop_instance_initialize_rotation_angles", 1866, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_remove_light", 1867, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_refill_hit_points", 1870, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_dynamics_set_properties", 1871, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_dynamics_set_velocity", 1872, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_dynamics_set_omega", 1873, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_dynamics_apply_impulse", 1874, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_receive_damage", 1877, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_intersects_with_prop_instance", 1880, Parameter.ScenePropIdentifier, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_play_sound", 1881, Parameter.ScenePropIdentifier, Parameter.SoundIdentifier),
                new Operator("prop_instance_stop_sound", 1882, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_sound_progress", 1883, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_clear_attached_missiles", 1885, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_add_particle_system", 1886, Parameter.ScenePropIdentifier, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("prop_instance_stop_all_particle_systems", 1887, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_remove_particle_system", 1888, Parameter.ScenePropIdentifier, Parameter.ParticleSystemIdentifier),
                new Operator("replace_prop_instance", 1889, Parameter.ScenePropIdentifier, Parameter.ScenePropIdentifier),
                new Operator("replace_scene_props", 1890, Parameter.ScenePropIdentifier, Parameter.ScenePropIdentifier),
                new Operator("replace_scene_items_with_scene_props", 1891, Parameter.ItemIdentifier, Parameter.ScenePropIdentifier),
                new Operator("cast_ray", 1900, Parameter.None, Parameter.Position, Parameter.Position, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("set_mission_result", 1906),
                new Operator("finish_mission", 1907),
                new Operator("jump_to_scene", 1910, Parameter.SceneIdentifier),
                new Operator("set_jump_mission", 1911, Parameter.MissionTemplateIdentifier),
                new Operator("set_jump_entry", 1912),
                new Operator("start_mission_conversation", 1920, Parameter.TroopIdentifier),
                new Operator("add_reinforcements_to_entry", 1930),
                new Operator("mission_enable_talk", 1935),
                new Operator("mission_disable_talk", 1936),
                new Operator("mission_tpl_entry_set_override_flags", 1940, Parameter.MissionTemplateIdentifier),
                new Operator("mission_tpl_entry_clear_override_items", 1941, Parameter.MissionTemplateIdentifier),
                new Operator("mission_tpl_entry_add_override_item", 1942, Parameter.MissionTemplateIdentifier, Parameter.None, Parameter.ItemIdentifier),
                new Operator("get_water_level", 1945),
                new Operator("set_current_color", 1950),
                new Operator("set_position_delta", 1955),
                new Operator("add_point_light", 1960),
                new Operator("add_point_light_to_entity", 1961),
                new Operator("cur_item_mesh_set_color", 1962, Parameter.MeshIdentifier),
                new Operator("cur_item_add_mesh_with_material", 1963, Parameter.String, Parameter.String),
                new Operator("cur_item_add_mesh", 1964, Parameter.String),
                new Operator("particle_system_add_new", 1965, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("particle_system_clear", 1966),
                new Operator("particle_system_emit", 1968, Parameter.ParticleSystemIdentifier),
                new Operator("particle_system_burst", 1969, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("set_spawn_position", 1970, Parameter.Position),
                new Operator("spawn_item", 1971, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("spawn_agent", 1972, Parameter.TroopIdentifier),
                new Operator("spawn_horse", 1973, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("spawn_scene_prop", 1974, Parameter.ScenePropIdentifier),
                new Operator("particle_system_burst_no_sync", 1975, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("spawn_item_without_refill", 1976, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("agent_get_item_cur_ammo", 1977),
                new Operator("cur_item_set_material", 1978, Parameter.String),
                new Operator("cur_tableau_add_terrain", 1979, Parameter.SceneIdentifier),
                new Operator("cur_tableau_add_tableau_mesh", 1980, Parameter.TableauMaterialIdentifier, Parameter.None, Parameter.Position),
                new Operator("cur_item_set_tableau_material", 1981, Parameter.TableauMaterialIdentifier),
                new Operator("cur_scene_prop_set_tableau_material", 1982, Parameter.TableauMaterialIdentifier),
                new Operator("cur_map_icon_set_tableau_material", 1983, Parameter.TableauMaterialIdentifier),
                new Operator("cur_tableau_render_as_alpha_mask", 1984),
                new Operator("cur_tableau_set_background_color", 1985),
                new Operator("cur_agent_set_banner_tableau_material", 1986, Parameter.TableauMaterialIdentifier),
                new Operator("cur_tableau_set_ambient_light", 1987),
                new Operator("cur_tableau_set_camera_position", 1988, Parameter.Position),
                new Operator("cur_tableau_set_camera_parameters", 1989),
                new Operator("cur_tableau_add_point_light", 1990, Parameter.Position),
                new Operator("cur_tableau_add_sun_light", 1991, Parameter.Position),
                new Operator("cur_tableau_add_mesh", 1992, Parameter.MeshIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_mesh_with_vertex_color", 1993, Parameter.MeshIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_map_icon", 1994, Parameter.MapIconIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_troop", 1995, Parameter.TroopIdentifier, Parameter.Position, Parameter.AnimationIdentifier),
                new Operator("cur_tableau_add_horse", 1996, Parameter.ItemIdentifier, Parameter.Position, Parameter.AnimationIdentifier),
                new Operator("cur_tableau_set_override_flags", 1997),
                new Operator("cur_tableau_clear_override_items", 1998),
                new Operator("cur_tableau_add_override_item", 1999, Parameter.ItemIdentifier),
                new Operator("cur_tableau_add_mesh_with_scale_and_vertex_color", 2000, Parameter.MeshIdentifier, Parameter.Position, Parameter.Position),
                new Operator("mission_cam_set_mode", 2001),
                new Operator("mission_get_time_speed", 2002),
                new Operator("mission_set_time_speed", 2003),
                new Operator("mission_time_speed_move_to_value", 2004),
                new Operator("mission_set_duel_mode", 2006),
                new Operator("mission_cam_set_screen_color", 2008),
                new Operator("mission_cam_animate_to_screen_color", 2009),
                new Operator("mission_cam_get_position", 2010, Parameter.Position),
                new Operator("mission_cam_set_position", 2011, Parameter.Position),
                new Operator("mission_cam_animate_to_position", 2012, Parameter.Position),
                new Operator("mission_cam_get_aperture", 2013),
                new Operator("mission_cam_set_aperture", 2014),
                new Operator("mission_cam_animate_to_aperture", 2015),
                new Operator("mission_cam_animate_to_position_and_aperture", 2016, Parameter.Position),
                new Operator("mission_cam_set_target_agent", 2017),
                new Operator("mission_cam_clear_target_agent", 2018),
                new Operator("mission_cam_set_animation", 2019, Parameter.AnimationIdentifier),
                new Operator("talk_info_show", 2020),
                new Operator("talk_info_set_relation_bar", 2021),
                new Operator("talk_info_set_line", 2022, Parameter.None, Parameter.String),
                new Operator("set_background_mesh", 2031, Parameter.MeshIdentifier),
                new Operator("set_game_menu_tableau_mesh", 2032, Parameter.TableauMaterialIdentifier, Parameter.None, Parameter.Position),
                new Operator("change_screen_return", 2040),
                new Operator("change_screen_loot", 2041, Parameter.TroopIdentifier),
                new Operator("change_screen_trade", 2042, Parameter.TroopIdentifier),
                new Operator("change_screen_exchange_members", 2043, Parameter.None, Parameter.None, Parameter.PartyIdentifier),
                new Operator("change_screen_trade_prisoners", 2044),
                new Operator("change_screen_buy_mercenaries", 2045),
                new Operator("change_screen_view_character", 2046, Parameter.TroopIdentifier),
                new Operator("change_screen_training", 2047),
                new Operator("change_screen_mission", 2048),
                new Operator("change_screen_map_conversation", 2049, Parameter.TroopIdentifier),
                new Operator("change_screen_exchange_with_party", 2050, Parameter.PartyIdentifier),
                new Operator("change_screen_equip_other", 2051, Parameter.TroopIdentifier),
                new Operator("change_screen_map", 2052),
                new Operator("change_screen_notes", 2053),
                new Operator("change_screen_quit", 2055),
                new Operator("change_screen_give_members", 2056, Parameter.PartyIdentifier),
                new Operator("change_screen_controls", 2057),
                new Operator("change_screen_options", 2058),
                new Operator("change_screen_class_selection", 2059, Parameter.TroopIdentifier),
                new Operator("jump_to_menu", 2060, Parameter.MenuIdentifier),
                new Operator("disable_menu_option", 2061),
                new Operator("agent_get_damage_modifier", 2065),
                new Operator("agent_get_accuracy_modifier", 2066),
                new Operator("agent_get_speed_modifier", 2067),
                new Operator("agent_get_reload_speed_modifier", 2068),
                new Operator("agent_get_use_speed_modifier", 2069),
                new Operator("store_trigger_param", 2070),
                new Operator("store_trigger_param_1", 2071),
                new Operator("store_trigger_param_2", 2072),
                new Operator("store_trigger_param_3", 2073),
                new Operator("set_trigger_result", 2075),
                new Operator("agent_get_current_ai_mesh_face_group", 2078),
                new Operator("agent_set_play_footstep_sound", 2079),
                new Operator("agent_ai_get_look_target", 2080),
                new Operator("agent_ai_get_move_target", 2081),
                new Operator("agent_ai_get_behavior_target", 2082),
                new Operator("agent_ai_set_can_crouch", 2083),
                new Operator("agent_get_animation_progress", 2084),
                new Operator("agent_notify_animation_progress", 2085),
                new Operator("agent_get_current_vertical_speed", 2086),
                new Operator("agent_set_current_vertical_speed", 2087),
                new Operator("agent_relocate_to_position", 2088, Parameter.None, Parameter.Position),
                new Operator("agent_set_horse_rotation_speed_modifier", 2089),
                new Operator("agent_set_max_hit_points", 2090),
                new Operator("agent_set_damage_modifier", 2091),
                new Operator("agent_set_accuracy_modifier", 2092),
                new Operator("agent_set_speed_modifier", 2093),
                new Operator("agent_set_reload_speed_modifier", 2094),
                new Operator("agent_set_use_speed_modifier", 2095),
                new Operator("agent_set_visibility", 2096),
                new Operator("agent_get_crouch_mode", 2097),
                new Operator("agent_set_crouch_mode", 2098),
                new Operator("val_lshift", 2100),
                new Operator("val_rshift", 2101),
                new Operator("val_add", 2105),
                new Operator("val_sub", 2106),
                new Operator("val_mul", 2107),
                new Operator("val_div", 2108),
                new Operator("val_mod", 2109),
                new Operator("val_min", 2110),
                new Operator("val_max", 2111),
                new Operator("val_clamp", 2112),
                new Operator("val_abs", 2113),
                new Operator("val_or", 2114),
                new Operator("val_and", 2115),
                new Operator("store_or", 2116),
                new Operator("store_and", 2117),
                new Operator("store_mod", 2119),
                new Operator("store_add", 2120),
                new Operator("store_sub", 2121),
                new Operator("store_mul", 2122),
                new Operator("store_div", 2123),
                new Operator("set_fixed_point_multiplier", 2124),
                new Operator("store_sqrt", 2125),
                new Operator("store_pow", 2126),
                new Operator("store_sin", 2127),
                new Operator("store_cos", 2128),
                new Operator("store_tan", 2129),
                new Operator("convert_to_fixed_point", 2130),
                new Operator("convert_from_fixed_point", 2131),
                new Operator("assign", 2133),
                new Operator("shuffle_range", 2134),
                new Operator("store_random", 2135),
                new Operator("store_random_in_range", 2136),
                new Operator("set_random_seed", 2137),
                new Operator("store_asin", 2140),
                new Operator("store_acos", 2141),
                new Operator("store_atan", 2142),
                new Operator("store_atan2", 2143),
                new Operator("store_troop_gold", 2149, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_num_free_stacks", 2154, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_num_free_prisoner_stacks", 2155, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_party_size", 2156, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_party_size_wo_prisoners", 2157, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_troop_kind_count", 2158),
                new Operator("store_num_regular_prisoners", 2159, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_troop_count_companions", 2160, Parameter.None, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("store_troop_count_prisoners", 2161, Parameter.None, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("store_item_kind_count", 2165, Parameter.None, Parameter.ItemIdentifier, Parameter.TroopIdentifier),
                new Operator("store_free_inventory_capacity", 2167, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_skill_level", 2170, Parameter.None, Parameter.SkillIdentifier, Parameter.TroopIdentifier),
                new Operator("store_character_level", 2171, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_attribute_level", 2172, Parameter.None, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("store_troop_faction", 2173, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_faction_of_troop", 2173, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_troop_health", 2175, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_proficiency_level", 2176, Parameter.None, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("store_relation", 2190, Parameter.None, Parameter.FactionIdentifier, Parameter.FactionIdentifier),
                new Operator("set_conversation_speaker_troop", 2197, Parameter.TroopIdentifier),
                new Operator("set_conversation_speaker_agent", 2198),
                new Operator("store_conversation_agent", 2199),
                new Operator("store_conversation_troop", 2200),
                new Operator("store_partner_faction", 2201),
                new Operator("store_encountered_party", 2202),
                new Operator("store_encountered_party2", 2203),
                new Operator("store_faction_of_party", 2204, Parameter.None, Parameter.PartyIdentifier),
                new Operator("set_encountered_party", 2205),
                new Operator("store_current_scene", 2211),
                new Operator("store_zoom_amount", 2220),
                new Operator("set_zoom_amount", 2221),
                new Operator("is_zoom_disabled", 2222),
                new Operator("store_item_value", 2230, Parameter.None, Parameter.ItemIdentifier),
                new Operator("store_troop_value", 2231, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_partner_quest", 2240),
                new Operator("store_random_quest_in_range", 2250),
                new Operator("store_random_troop_to_raise", 2251),
                new Operator("store_random_troop_to_capture", 2252),
                new Operator("store_random_party_in_range", 2254),
                new Operator("store01_random_parties_in_range", 2255),
                new Operator("store_random_horse", 2257),
                new Operator("store_random_equipment", 2258),
                new Operator("store_random_armor", 2259),
                new Operator("store_quest_number", 2261, Parameter.None, Parameter.QuestIdentifier),
                new Operator("store_quest_item", 2262, Parameter.None, Parameter.ItemIdentifier),
                new Operator("store_quest_troop", 2263, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_current_hours", 2270),
                new Operator("store_time_of_day", 2271),
                new Operator("store_current_day", 2272),
                new Operator("is_currently_night", 2273),
                new Operator("store_distance_to_party_from_party", 2281, Parameter.None, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_switch_stacks", 2285, Parameter.PartyIdentifier),
                new Operator("get_party_ai_behavior", 2290, Parameter.None, Parameter.PartyIdentifier),
                new Operator("get_party_ai_object", 2291, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_ai_target_position", 2292, Parameter.Position, Parameter.PartyIdentifier),
                new Operator("get_party_ai_current_behavior", 2293, Parameter.None, Parameter.PartyIdentifier),
                new Operator("get_party_ai_current_object", 2294, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_num_parties_created", 2300, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_destroyed", 2301, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_destroyed_by_player", 2302, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_of_template", 2310, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_random_party_of_template", 2311),
                new Operator("str_is_empty", 2318, Parameter.String),
                new Operator("str_clear", 2319, Parameter.String),
                new Operator("str_store_string", 2320, Parameter.String, Parameter.String),
                new Operator("str_store_string_reg", 2321, Parameter.String, Parameter.String),
                new Operator("str_store_troop_name", 2322, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_troop_name_plural", 2323, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_troop_name_by_count", 2324, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_item_name", 2325, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_item_name_plural", 2326, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_item_name_by_count", 2327, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_party_name", 2330, Parameter.String, Parameter.PartyIdentifier),
                new Operator("str_store_agent_name", 2332, Parameter.String),
                new Operator("str_store_faction_name", 2335, Parameter.String, Parameter.FactionIdentifier),
                new Operator("str_store_quest_name", 2336, Parameter.String, Parameter.QuestIdentifier),
                new Operator("str_store_info_page_name", 2337, Parameter.String, Parameter.InfoPageIdentifier),
                new Operator("str_store_date", 2340, Parameter.String),
                new Operator("str_store_troop_name_link", 2341, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_party_name_link", 2342, Parameter.String, Parameter.PartyIdentifier),
                new Operator("str_store_faction_name_link", 2343, Parameter.String, Parameter.FactionIdentifier),
                new Operator("str_store_quest_name_link", 2344, Parameter.String, Parameter.QuestIdentifier),
                new Operator("str_store_info_page_name_link", 2345, Parameter.String, Parameter.InfoPageIdentifier),
                new Operator("str_store_class_name", 2346),
                new Operator("str_store_player_username", 2350, Parameter.String),
                new Operator("str_store_server_password", 2351, Parameter.String),
                new Operator("str_store_server_name", 2352, Parameter.String),
                new Operator("str_store_welcome_message", 2353, Parameter.String),
                new Operator("str_encode_url", 2355, Parameter.String),
                new Operator("str_store_skill_name", 2356, Parameter.String, Parameter.SkillIdentifier),
                new Operator("str_store_skill_desc", 2357, Parameter.String, Parameter.SkillIdentifier),
                new Operator("str_store_script_stack", 2358, Parameter.String),
                new Operator("store_remaining_team_no", 2360),
                new Operator("store_application_time", 2361),
                new Operator("store_mission_timer_a_msec", 2365),
                new Operator("store_mission_timer_b_msec", 2366),
                new Operator("store_mission_timer_c_msec", 2367),
                new Operator("store_mission_timer_a", 2370),
                new Operator("store_mission_timer_b", 2371),
                new Operator("store_mission_timer_c", 2372),
                new Operator("reset_mission_timer_a", 2375),
                new Operator("reset_mission_timer_b", 2376),
                new Operator("reset_mission_timer_c", 2377),
                new Operator("set_cheer_at_no_enemy", 2379),
                new Operator("store_enemy_count", 2380),
                new Operator("store_friend_count", 2381),
                new Operator("store_ally_count", 2382),
                new Operator("store_defender_count", 2383),
                new Operator("store_attacker_count", 2384),
                new Operator("store_normalized_team_count", 2385),
                new Operator("set_postfx", 2386),
                new Operator("set_river_shader_to_mud", 2387),
                new Operator("show_troop_details", 2388, Parameter.TroopIdentifier, Parameter.Position),
                new Operator("set_skybox", 2389),
                new Operator("set_startup_sun_light", 2390),
                new Operator("set_startup_ambient_light", 2391),
                new Operator("set_startup_ground_ambient_light", 2392),
                new Operator("rebuild_shadow_map", 2393),
                new Operator("set_shader_param_int", 2400),
                new Operator("set_shader_param_float", 2401),
                new Operator("set_shader_param_float4", 2402),
                new Operator("set_shader_param_float4x4", 2403),
                new Operator("show_crosshair", 2500),
                new Operator("show_hud", 2501),
                new Operator("enable_orders", 2502),
                new Operator("is_party_skill", 2540, Parameter.SkillIdentifier),
                new Operator("ai_mesh_face_group_translate", 2550, Parameter.None, Parameter.Position),
                new Operator("prop_instance_set_forced_lod", 2600, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_deform_to_time", 2610, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_deform_in_range", 2611, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_deform_in_cycle_loop", 2612),
                new Operator("prop_instance_get_current_deform_progress", 2615, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_current_deform_frame", 2616, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_material", 2617, Parameter.ScenePropIdentifier, Parameter.None, Parameter.String),
                new Operator("agent_attack_scene_prop_instance", 2650, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("agent_get_horse_rotation_velocity", 2655),
                new Operator("agent_get_position_in_group", 2660, Parameter.Position),
                new Operator("item_get_weight", 2700, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_value", 2701, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_difficulty", 2702, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_head_armor", 2703, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_body_armor", 2704, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_leg_armor", 2705, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_hit_points", 2706, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_weapon_length", 2707, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_speed_rating", 2708, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_missile_speed", 2709, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_max_ammo", 2710, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_accuracy", 2711, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_shield_height", 2712, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_scale", 2713, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_speed", 2714, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_maneuver", 2715, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_food_quality", 2716, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_abundance", 2717, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_thrust_damage", 2718, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_thrust_damage_type", 2719, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_swing_damage", 2720, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_swing_damage_type", 2721, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_charge_damage", 2722, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_has_property", 2723, Parameter.ItemIdentifier, Parameter.ItemProperty),
                new Operator("item_has_capability", 2724, Parameter.ItemIdentifier, Parameter.ItemCapability),
                new Operator("item_has_modifier", 2725, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("item_has_faction", 2726, Parameter.ItemIdentifier, Parameter.FactionIdentifier),
                new Operator("str_store_agent_face_keys", 2749, Parameter.String),
                new Operator("str_store_troop_face_keys", 2750, Parameter.String, Parameter.TroopIdentifier),
                new Operator("troop_set_face_keys", 2751, Parameter.TroopIdentifier, Parameter.String),
                new Operator("face_keys_get_hair", 2752, Parameter.None, Parameter.String),
                new Operator("face_keys_set_hair", 2753, Parameter.String),
                new Operator("face_keys_get_beard", 2754, Parameter.None, Parameter.String),
                new Operator("face_keys_set_beard", 2755, Parameter.String),
                new Operator("face_keys_get_face_texture", 2756, Parameter.None, Parameter.String),
                new Operator("face_keys_set_face_texture", 2757, Parameter.String),
                new Operator("face_keys_get_hair_texture", 2758, Parameter.None, Parameter.String),
                new Operator("face_keys_set_hair_texture", 2759, Parameter.String),
                new Operator("face_keys_get_hair_color", 2760, Parameter.None, Parameter.String),
                new Operator("face_keys_set_hair_color", 2761, Parameter.String),
                new Operator("face_keys_get_age", 2762, Parameter.None, Parameter.String),
                new Operator("face_keys_set_age", 2763, Parameter.String),
                new Operator("face_keys_get_skin_color", 2764, Parameter.None, Parameter.String),
                new Operator("face_keys_set_skin_color", 2765, Parameter.String),
                new Operator("face_keys_get_morph_key", 2766, Parameter.None, Parameter.String, Parameter.KeyCode),
                new Operator("face_keys_set_morph_key", 2767, Parameter.String, Parameter.KeyCode),
            };
        }
    }
}
