using System.Collections.Generic;

namespace Decomp.Core.Operators
{
    public class VanillaVersion : IGameVersion
    {
        public IEnumerable<Operator> GetOperators()
        {
            return new List<Operator>
            {
                new Operator("call_script", 1, Parameter.ScriptIdentifier),
                new Operator("end_try", 3),
                new Operator("try_end", 3),
                new Operator("try_begin", 4),
                new Operator("else_try_begin", 5),
                new Operator("else_try", 5),
                new Operator("try_for_range", 6),
                new Operator("try_for_range_backwards", 7),
                new Operator("try_for_parties", 11),
                new Operator("try_for_agents", 12),
                new Operator("store_script_param_1", 21),
                new Operator("store_script_param_2", 22),
                new Operator("store_script_param", 23),
                new Operator("ge", 30),
                new Operator("eq", 31),
                new Operator("gt", 32),
                new Operator("is_between", 33),
                new Operator("entering_town", 36, Parameter.PartyIdentifier),
                new Operator("map_free", 37),
                new Operator("encountered_party_is_attacker", 39),
                new Operator("conversation_screen_is_active", 42),
                new Operator("in_meta_mission", 44),
                new Operator("set_player_troop", 47, Parameter.TroopIdentifier),
                new Operator("store_repeat_object", 50),
                new Operator("set_result_string", 60, Parameter.String),
                new Operator("key_is_down", 70, Parameter.KeyCode),
                new Operator("key_clicked", 71, Parameter.KeyCode),
                new Operator("game_key_is_down", 72),
                new Operator("game_key_clicked", 73),
                new Operator("mouse_get_position", 75, Parameter.Position),
                new Operator("get_global_cloud_amount", 90),
                new Operator("set_global_cloud_amount", 91),
                new Operator("get_global_haze_amount", 92),
                new Operator("set_global_haze_amount", 93),
                new Operator("hero_can_join", 101, Parameter.PartyIdentifier),
                new Operator("hero_can_join_as_prisoner", 102, Parameter.PartyIdentifier),
                new Operator("party_can_join", 103),
                new Operator("party_can_join_as_prisoner", 104),
                new Operator("troops_can_join", 105),
                new Operator("troops_can_join_as_prisoner", 106),
                new Operator("party_can_join_party", 107, Parameter.None, Parameter.PartyIdentifier),
                new Operator("main_party_has_troop", 110, Parameter.TroopIdentifier),
                new Operator("party_is_in_town", 130),
                new Operator("party_is_in_any_town", 131, Parameter.PartyIdentifier),
                new Operator("party_is_active", 132, Parameter.PartyIdentifier),
                new Operator("player_has_item", 150, Parameter.ItemIdentifier),
                new Operator("troop_has_item_equipped", 151, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_is_mounted", 152, Parameter.TroopIdentifier),
                new Operator("troop_is_guarantee_ranged", 153, Parameter.TroopIdentifier),
                new Operator("troop_is_guarantee_horse", 154, Parameter.TroopIdentifier),
                new Operator("check_quest_active", 200, Parameter.QuestIdentifier),
                new Operator("check_quest_finished", 201, Parameter.QuestIdentifier),
                new Operator("check_quest_succeeded", 202, Parameter.QuestIdentifier),
                new Operator("check_quest_failed", 203, Parameter.QuestIdentifier),
                new Operator("check_quest_concluded", 204, Parameter.QuestIdentifier),
                new Operator("troop_set_slot", 500, Parameter.TroopIdentifier),
                new Operator("party_set_slot", 501, Parameter.PartyIdentifier),
                new Operator("faction_set_slot", 502, Parameter.FactionIdentifier),
                new Operator("scene_set_slot", 503, Parameter.SceneIdentifier),
                new Operator("party_template_set_slot", 504, Parameter.PartyTemplateIdentifier),
                new Operator("agent_set_slot", 505),
                new Operator("quest_set_slot", 506, Parameter.QuestIdentifier),
                new Operator("item_set_slot", 507, Parameter.ItemIdentifier),
                new Operator("troop_get_slot", 520, Parameter.None, Parameter.TroopIdentifier),
                new Operator("party_get_slot", 521, Parameter.None, Parameter.PartyIdentifier),
                new Operator("faction_get_slot", 522, Parameter.None, Parameter.FactionIdentifier),
                new Operator("scene_get_slot", 523, Parameter.None, Parameter.SceneIdentifier),
                new Operator("party_template_get_slot", 524, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("agent_get_slot", 525),
                new Operator("quest_get_slot", 526, Parameter.None, Parameter.QuestIdentifier),
                new Operator("item_get_slot", 527, Parameter.None, Parameter.ItemIdentifier),
                new Operator("troop_slot_eq", 540, Parameter.TroopIdentifier),
                new Operator("party_slot_eq", 541, Parameter.PartyIdentifier),
                new Operator("faction_slot_eq", 542, Parameter.FactionIdentifier),
                new Operator("scene_slot_eq", 543, Parameter.SceneIdentifier),
                new Operator("party_template_slot_eq", 544, Parameter.PartyTemplateIdentifier),
                new Operator("agent_slot_eq", 545),
                new Operator("quest_slot_eq", 546, Parameter.QuestIdentifier),
                new Operator("item_slot_eq", 547, Parameter.ItemIdentifier),
                new Operator("troop_slot_ge", 560, Parameter.TroopIdentifier),
                new Operator("party_slot_ge", 561, Parameter.PartyIdentifier),
                new Operator("faction_slot_ge", 562, Parameter.FactionIdentifier),
                new Operator("scene_slot_ge", 563, Parameter.SceneIdentifier),
                new Operator("party_template_slot_ge", 564, Parameter.PartyTemplateIdentifier),
                new Operator("agent_slot_ge", 565),
                new Operator("quest_slot_ge", 566, Parameter.QuestIdentifier),
                new Operator("item_slot_ge", 567, Parameter.ItemIdentifier),
                new Operator("play_sound", 600, Parameter.SoundIdentifier),
                new Operator("play_track", 601, Parameter.TrackIdentifier),
                new Operator("play_cue_track", 602, Parameter.TrackIdentifier),
                new Operator("music_set_situation", 603, Parameter.MusicFlags),
                new Operator("music_set_culture", 604, Parameter.MusicFlags),
                new Operator("stop_all_sounds", 609),
                new Operator("copy_position", 700, Parameter.Position, Parameter.Position),
                new Operator("init_position", 701, Parameter.Position),
                new Operator("get_trigger_object_position", 702, Parameter.Position),
                new Operator("get_distance_between_positions", 710, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("position_is_behind_position", 713, Parameter.Position, Parameter.Position),
                new Operator("position_transform_position_to_parent", 715, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_transform_position_to_local", 716, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_copy_rotation", 718, Parameter.Position, Parameter.Position),
                new Operator("position_copy_origin", 719, Parameter.Position, Parameter.Position),
                new Operator("position_move_x", 720, Parameter.Position),
                new Operator("position_move_y", 721, Parameter.Position),
                new Operator("position_move_z", 722, Parameter.Position),
                new Operator("position_rotate_x", 723, Parameter.Position),
                new Operator("position_rotate_y", 724, Parameter.Position),
                new Operator("position_rotate_z", 725, Parameter.Position),
                new Operator("position_get_x", 726, Parameter.None, Parameter.Position),
                new Operator("position_get_y", 727, Parameter.None, Parameter.Position),
                new Operator("position_get_z", 728, Parameter.None, Parameter.Position),
                new Operator("position_set_x", 729, Parameter.Position),
                new Operator("position_set_y", 730, Parameter.Position),
                new Operator("position_set_z", 731, Parameter.Position),
                new Operator("position_get_scale_x", 735, Parameter.None, Parameter.Position),
                new Operator("position_get_scale_y", 736, Parameter.None, Parameter.Position),
                new Operator("position_get_scale_z", 737, Parameter.None, Parameter.Position),
                new Operator("position_get_rotation_around_z", 740, Parameter.None, Parameter.Position),
                new Operator("position_normalize_origin", 741, Parameter.None, Parameter.Position),
                new Operator("position_set_z_to_ground_level", 791, Parameter.Position),
                new Operator("start_presentation", 900, Parameter.PresentationIdentifier),
                new Operator("start_background_presentation", 901, Parameter.PresentationIdentifier),
                new Operator("presentation_set_duration", 902),
                new Operator("create_text_overlay", 910, Parameter.None, Parameter.String),
                new Operator("create_mesh_overlay", 911, Parameter.None, Parameter.MeshIdentifier),
                new Operator("create_button_overlay", 912, Parameter.None, Parameter.String),
                new Operator("create_image_button_overlay", 913, Parameter.None, Parameter.MeshIdentifier, Parameter.MeshIdentifier),
                new Operator("create_slider_overlay", 914),
                new Operator("create_progress_overlay", 915),
                new Operator("create_combo_button_overlay", 916),
                new Operator("create_text_box_overlay", 917),
                new Operator("create_check_box_overlay", 918),
                new Operator("overlay_set_text", 920, Parameter.None, Parameter.String),
                new Operator("overlay_set_color", 921),
                new Operator("overlay_set_alpha", 922, Parameter.None, Parameter.Alpha),
                new Operator("overlay_set_hilight_color", 923),
                new Operator("overlay_set_hilight_alpha", 924, Parameter.None, Parameter.Alpha),
                new Operator("overlay_set_size", 925, Parameter.None, Parameter.Position),
                new Operator("overlay_set_position", 926, Parameter.None, Parameter.Position),
                new Operator("overlay_set_val", 927),
                new Operator("overlay_set_boundaries", 928),
                new Operator("overlay_set_area_size", 929, Parameter.None, Parameter.Position),
                new Operator("overlay_set_mesh_rotation", 930, Parameter.None, Parameter.Position),
                new Operator("overlay_add_item", 931, Parameter.None, Parameter.String),
                new Operator("overlay_animate_to_color", 932),
                new Operator("overlay_animate_to_alpha", 933),
                new Operator("overlay_animate_to_highlight_color", 934),
                new Operator("overlay_animate_to_highlight_alpha", 935),
                new Operator("overlay_animate_to_size", 936, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("overlay_animate_to_position", 937, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("create_image_button_overlay_with_tableau_material", 938, Parameter.None, Parameter.MeshIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("create_mesh_overlay_with_tableau_material", 939, Parameter.None, Parameter.MeshIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("create_game_button_overlay", 940, Parameter.None, Parameter.String),
                new Operator("context_menu_add_item", 980, Parameter.String),
                new Operator("get_average_game_difficulty", 990),
                new Operator("all_enemies_defeated", 1003),
                new Operator("race_completed_by_player", 1004),
                new Operator("num_active_teams_le", 1005),
                new Operator("main_hero_fallen", 1006),
                new Operator("set_party_battle_mode", 1020),
                new Operator("set_camera_follow_party", 1021, Parameter.PartyIdentifier),
                new Operator("start_map_conversation", 1025, Parameter.TroopIdentifier),
                new Operator("rest_for_hours", 1030),
                new Operator("rest_for_hours_interactive", 1031),
                new Operator("add_xp_to_troop", 1062, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_gold_as_xp", 1063, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_xp_as_reward", 1064),
                new Operator("add_gold_to_party", 1070, Parameter.None, Parameter.PartyIdentifier),
                new Operator("set_party_creation_random_limits", 1080),
                new Operator("spawn_around_party", 1100, Parameter.PartyIdentifier, Parameter.PartyTemplateIdentifier),
                new Operator("set_spawn_radius", 1103),
                new Operator("display_log_message", 1105, Parameter.String, Parameter.Color),
                new Operator("display_message", 1106, Parameter.String, Parameter.Color),
                new Operator("set_show_messages", 1107),
                new Operator("add_troop_note_tableau_mesh", 1108, Parameter.TroopIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_faction_note_tableau_mesh", 1109, Parameter.TroopIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_party_note_tableau_mesh", 1110, Parameter.TroopIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_quest_note_tableau_mesh", 1111, Parameter.TroopIdentifier, Parameter.TableauMaterialIdentifier),
                new Operator("add_troop_note_from_dialog", 1114, Parameter.TroopIdentifier),
                new Operator("add_faction_note_from_dialog", 1115, Parameter.FactionIdentifier),
                new Operator("add_party_note_from_dialog", 1116, Parameter.PartyIdentifier),
                new Operator("add_quest_note_from_dialog", 1112, Parameter.QuestIdentifier),
                new Operator("add_troop_note_from_sreg", 1117, Parameter.TroopIdentifier, Parameter.None, Parameter.String),
                new Operator("add_faction_note_from_sreg", 1118, Parameter.FactionIdentifier, Parameter.None, Parameter.String),
                new Operator("add_party_note_from_sreg", 1119, Parameter.PartyIdentifier, Parameter.None, Parameter.String),
                new Operator("add_quest_note_from_sreg", 1113, Parameter.QuestIdentifier, Parameter.None, Parameter.String),
                new Operator("tutorial_box", 1120, Parameter.String, Parameter.String),
                new Operator("dialog_box", 1120, Parameter.String, Parameter.String),
                new Operator("question_box", 1121, Parameter.String, Parameter.String, Parameter.String),
                new Operator("tutorial_message", 1122, Parameter.String),
                new Operator("reset_price_rates", 1170),
                new Operator("set_price_rate_for_item", 1171, Parameter.ItemIdentifier),
                new Operator("set_price_rate_for_item_type", 1172, Parameter.ItemType),
                new Operator("party_join", 1201),
                new Operator("party_join_as_prisoner", 1202),
                new Operator("troop_join", 1203, Parameter.TroopIdentifier),
                new Operator("troop_join_as_prisoner", 1204, Parameter.TroopIdentifier),
                new Operator("remove_member_from_party", 1210, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("remove_regular_prisoners", 1211, Parameter.PartyIdentifier),
                new Operator("remove_troops_from_companions", 1215, Parameter.TroopIdentifier),
                new Operator("remove_troops_from_prisoners", 1216, Parameter.TroopIdentifier),
                new Operator("heal_party", 1225, Parameter.PartyIdentifier),
                new Operator("disable_party", 1230, Parameter.PartyIdentifier),
                new Operator("enable_party", 1231, Parameter.PartyIdentifier),
                new Operator("remove_party", 1232, Parameter.PartyIdentifier),
                new Operator("add_companion_party", 1233),
                new Operator("add_troop_to_site", 1250, Parameter.TroopIdentifier, Parameter.SceneIdentifier),
                new Operator("remove_troop_from_site", 1251, Parameter.TroopIdentifier, Parameter.SceneIdentifier),
                new Operator("modify_visitors_at_site", 1261, Parameter.SceneIdentifier),
                new Operator("reset_visitors", 1262),
                new Operator("set_visitor", 1263, Parameter.None, Parameter.TroopIdentifier),
                new Operator("set_visitors", 1264, Parameter.None, Parameter.TroopIdentifier),
                new Operator("add_visitors_to_current_scene", 1265, Parameter.None, Parameter.TroopIdentifier),
                new Operator("set_relation", 1270, Parameter.FactionIdentifier, Parameter.FactionIdentifier),
                new Operator("faction_set_name", 1275, Parameter.FactionIdentifier, Parameter.String),
                new Operator("faction_set_color", 1276, Parameter.FactionIdentifier),
                new Operator("start_quest", 1280, Parameter.QuestIdentifier),
                new Operator("complete_quest", 1281, Parameter.QuestIdentifier),
                new Operator("succeed_quest", 1282, Parameter.QuestIdentifier),
                new Operator("fail_quest", 1283, Parameter.QuestIdentifier),
                new Operator("cancel_quest", 1284, Parameter.QuestIdentifier),
                new Operator("set_quest_progression", 1285, Parameter.QuestIdentifier),
                new Operator("conclude_quest", 1286, Parameter.QuestIdentifier),
                new Operator("setup_quest_text", 1290, Parameter.QuestIdentifier),
                new Operator("setup_quest_giver", 1291, Parameter.QuestIdentifier, Parameter.String),
                new Operator("start_encounter", 1300, Parameter.PartyIdentifier),
                new Operator("leave_encounter", 1301),
                new Operator("encounter_attack", 1302),
                new Operator("select_enemy", 1303),
                new Operator("set_passage_menu", 1304),
                new Operator("end_current_battle", 1307),
                new Operator("set_mercenary_source_party", 1320, Parameter.PartyIdentifier),
                new Operator("set_merchandise_modifier_quality", 1490),
                new Operator("set_merchandise_max_value", 1491),
                new Operator("reset_item_probabilities", 1492),
                new Operator("set_item_probability_in_merchandise", 1493, Parameter.ItemIdentifier),
                new Operator("troop_set_type", 1505, Parameter.TroopIdentifier),
                new Operator("troop_get_type", 1506, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_is_hero", 1507, Parameter.TroopIdentifier),
                new Operator("troop_is_wounded", 1508, Parameter.TroopIdentifier),
                new Operator("troop_set_auto_equip", 1509, Parameter.TroopIdentifier),
                new Operator("troop_ensure_inventory_space", 1510, Parameter.TroopIdentifier),
                new Operator("troop_sort_inventory", 1511, Parameter.TroopIdentifier),
                new Operator("troop_add_merchandise", 1512, Parameter.TroopIdentifier, Parameter.ItemType),
                new Operator("troop_get_xp", 1515, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_raise_attribute", 1520, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("troop_raise_skill", 1521, Parameter.TroopIdentifier, Parameter.SkillIdentifier),
                new Operator("troop_raise_proficiency", 1522, Parameter.TroopIdentifier, Parameter.WeaponProficiency),
                new Operator("troop_raise_proficiency_linear", 1523, Parameter.TroopIdentifier, Parameter.WeaponProficiency),
                new Operator("troop_add_proficiency_points", 1525, Parameter.TroopIdentifier),
                new Operator("troop_add_gold", 1528, Parameter.TroopIdentifier),
                new Operator("troop_remove_gold", 1529, Parameter.TroopIdentifier),
                new Operator("troop_add_item", 1530, Parameter.TroopIdentifier, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("troop_remove_item", 1531, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_clear_inventory", 1532, Parameter.TroopIdentifier),
                new Operator("troop_equip_items", 1533, Parameter.TroopIdentifier),
                new Operator("troop_inventory_slot_set_item_amount", 1534, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_inventory_slot_get_item_amount", 1537, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_inventory_slot_get_item_max_amount", 1538, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_add_items", 1535, Parameter.TroopIdentifier, Parameter.ItemIdentifier),
                new Operator("troop_remove_items", 1536),
                new Operator("troop_loot_troop", 1539, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_get_inventory_capacity", 1540, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_get_inventory_slot", 1541, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_get_inventory_slot_modifier", 1542, Parameter.None, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_inventory_slot", 1543, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_inventory_slot_modifier", 1544, Parameter.TroopIdentifier, Parameter.InventorySlot),
                new Operator("troop_set_faction", 1550, Parameter.TroopIdentifier, Parameter.FactionIdentifier),
                new Operator("troop_set_health", 1560, Parameter.TroopIdentifier),
                new Operator("troop_get_upgrade_troop", 1561, Parameter.None, Parameter.TroopIdentifier),
                new Operator("item_get_type", 1570, Parameter.None, Parameter.ItemIdentifier),
                new Operator("party_get_num_companions", 1601, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_prisoners", 1602, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_flags", 1603, Parameter.PartyIdentifier),
                new Operator("party_set_extra_text", 1605, Parameter.PartyIdentifier, Parameter.String),
                new Operator("party_get_current_terrain", 1608, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_template_id", 1609, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_add_members", 1610, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_add_prisoners", 1611, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_add_leader", 1612, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_force_add_members", 1613, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_force_add_prisoners", 1614, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_remove_members", 1615, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_remove_prisoners", 1616, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_clear", 1617, Parameter.PartyIdentifier),
                new Operator("party_wound_members", 1618, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_remove_members_wounded_first", 1619, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_set_faction", 1620, Parameter.PartyIdentifier, Parameter.FactionIdentifier),
                new Operator("party_relocate_near_party", 1623, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_get_position", 1625, Parameter.Position, Parameter.PartyIdentifier),
                new Operator("party_set_position", 1626, Parameter.PartyIdentifier, Parameter.Position),
                new Operator("map_get_random_position_around_position", 1627, Parameter.Position, Parameter.Position),
                new Operator("map_get_land_position_around_position", 1628, Parameter.Position, Parameter.Position),
                new Operator("map_get_water_position_around_position", 1629, Parameter.Position, Parameter.Position),
                new Operator("party_count_members_of_type", 1630, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_count_companions_of_type", 1631, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_count_prisoners_of_type", 1632, Parameter.None, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("party_get_free_companions_capacity", 1633, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_free_prisoners_capacity", 1634, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_ai_initiative", 1639, Parameter.PartyIdentifier),
                new Operator("party_set_ai_behavior", 1640, Parameter.PartyIdentifier, Parameter.AiBehavior),
                new Operator("party_set_ai_object", 1641, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_set_ai_target_position", 1642, Parameter.PartyIdentifier, Parameter.Position),
                new Operator("party_set_ai_patrol_radius", 1643, Parameter.PartyIdentifier),
                new Operator("party_ignore_player", 1644, Parameter.PartyIdentifier),
                new Operator("party_set_bandit_attraction", 1645, Parameter.PartyIdentifier),
                new Operator("party_get_num_companion_stacks", 1650, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_prisoner_stacks", 1651, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_troop_id", 1652, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_size", 1653, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_num_wounded", 1654, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_troop_dna", 1655, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_troop_id", 1656, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_size", 1657, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_prisoner_stack_get_troop_dna", 1658, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_attach_to_party", 1660, Parameter.PartyIdentifier),
                new Operator("party_detach", 1661, Parameter.PartyIdentifier),
                new Operator("party_collect_attachments_to_party", 1662, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("party_quick_attach_to_current_battle", 1663, Parameter.PartyIdentifier),
                new Operator("party_get_cur_town", 1665, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_leave_cur_battle", 1666, Parameter.PartyIdentifier),
                new Operator("party_set_next_battle_simulation_time", 1667, Parameter.PartyIdentifier),
                new Operator("party_set_name", 1669, Parameter.PartyIdentifier, Parameter.String),
                new Operator("party_add_xp_to_stack", 1670, Parameter.PartyIdentifier),
                new Operator("party_get_morale", 1671, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_set_morale", 1672, Parameter.PartyIdentifier),
                new Operator("party_upgrade_with_xp", 1673, Parameter.PartyIdentifier),
                new Operator("party_add_xp", 1674, Parameter.PartyIdentifier),
                new Operator("party_add_template", 1675, Parameter.PartyIdentifier, Parameter.PartyTemplateIdentifier),
                new Operator("party_set_icon", 1676, Parameter.PartyIdentifier, Parameter.MapIconIdentifier),
                new Operator("party_set_banner_icon", 1677, Parameter.PartyIdentifier, Parameter.MapIconIdentifier),
                new Operator("party_add_particle_system", 1678, Parameter.PartyIdentifier, Parameter.ParticleSystemIdentifier),
                new Operator("party_clear_particle_systems", 1679, Parameter.PartyIdentifier),
                new Operator("party_get_battle_opponent", 1680, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_icon", 1681, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_skill_level", 1685, Parameter.None, Parameter.PartyIdentifier, Parameter.SkillIdentifier),
                new Operator("get_battle_advantage", 1690),
                new Operator("set_battle_advantage", 1691),
                new Operator("party_get_attached_to", 1694, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_num_attached_parties", 1695, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_attached_party_with_rank", 1696, Parameter.None, Parameter.PartyIdentifier),
                new Operator("inflict_casualties_to_party_group", 1697, Parameter.PartyIdentifier, Parameter.None, Parameter.PartyIdentifier),
                new Operator("distribute_party_among_party_group", 1698, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("get_player_agent_no", 1700),
                new Operator("get_player_agent_kill_count", 1701),
                new Operator("agent_is_alive", 1702),
                new Operator("agent_is_wounded", 1703),
                new Operator("agent_is_human", 1704),
                new Operator("get_player_agent_own_troop_kill_count", 1705),
                new Operator("agent_is_ally", 1706),
                new Operator("agent_is_defender", 1708),
                new Operator("agent_get_look_position", 1709, Parameter.Position),
                new Operator("agent_get_position", 1710, Parameter.Position),
                new Operator("agent_set_position", 1711, Parameter.None, Parameter.Position),
                new Operator("agent_get_horse", 1714),
                new Operator("agent_get_rider", 1715),
                new Operator("agent_get_party_id", 1716),
                new Operator("agent_get_entry_no", 1717),
                new Operator("agent_get_troop_id", 1718),
                new Operator("agent_get_item_id", 1719),
                new Operator("store_agent_hit_points", 1720),
                new Operator("agent_set_hit_points", 1721),
                new Operator("agent_deliver_damage_to_agent", 1722),
                new Operator("agent_get_kill_count", 1723),
                new Operator("agent_get_wielded_item", 1726),
                new Operator("agent_get_ammo", 1727),
                new Operator("agent_refill_ammo", 1728),
                new Operator("agent_has_item_equipped", 1729, Parameter.None, Parameter.ItemIdentifier),
                new Operator("agent_set_scripted_destination", 1730, Parameter.None, Parameter.Position),
                new Operator("agent_get_scripted_destination", 1731, Parameter.Position),
                new Operator("agent_clear_scripted_mode", 1735),
                new Operator("agent_set_speed_limit", 1736),
                new Operator("agent_ai_set_always_attack_in_melee", 1737),
                new Operator("agent_get_simple_behavior", 1738),
                new Operator("agent_get_combat_state", 1739),
                new Operator("agent_set_animation", 1740, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_stand_animation", 1741, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_walk_forward_animation", 1742, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_animation_progress", 1743),
                new Operator("agent_play_sound", 1750, Parameter.None, Parameter.SoundIdentifier),
                new Operator("agent_get_team", 1770),
                new Operator("agent_set_team", 1771),
                new Operator("agent_get_class", 1772),
                new Operator("class_is_listening_order", 1775),
                new Operator("entry_point_get_position", 1780, Parameter.Position),
                new Operator("team_get_hold_fire_order", 1784),
                new Operator("team_get_movement_order", 1785),
                new Operator("team_get_riding_order", 1786),
                new Operator("team_get_weapon_usage_order", 1787),
                new Operator("teams_are_enemies", 1788),
                new Operator("team_give_order", 1790),
                new Operator("team_set_order_position", 1791, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("team_get_leader", 1792),
                new Operator("team_set_leader", 1793),
                new Operator("team_get_order_position", 1794, Parameter.Position),
                new Operator("team_set_order_listener", 1795),
                new Operator("team_set_relation", 1796),
                new Operator("set_rain", 1797),
                new Operator("set_fog_distance", 1798, Parameter.None, Parameter.Color),
                new Operator("get_scene_boundaries", 1799, Parameter.Position, Parameter.Position),
                new Operator("scene_prop_get_num_instances", 1810, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("scene_prop_get_instance", 1811, Parameter.None, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_position", 1850, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_starting_position", 1851, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_get_scale", 1852, Parameter.Position, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_position", 1855, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("prop_instance_animate_to_position", 1860, Parameter.ScenePropIdentifier, Parameter.Position),
                new Operator("replace_scene_props", 1890, Parameter.ScenePropIdentifier, Parameter.ScenePropIdentifier),
                new Operator("set_mission_result", 1906),
                new Operator("finish_mission", 1907),
                new Operator("jump_to_scene", 1910, Parameter.SceneIdentifier),
                new Operator("set_jump_mission", 1911, Parameter.MissionTemplateIdentifier),
                new Operator("set_jump_entry", 1912),
                new Operator("start_mission_conversation", 1920, Parameter.TroopIdentifier),
                new Operator("add_reinforcements_to_entry", 1930),
                new Operator("mission_enable_talk", 1935),
                new Operator("mission_disable_talk", 1936),
                new Operator("mission_tpl_entry_set_override_flags", 1940, Parameter.MissionTemplateIdentifier),
                new Operator("mission_tpl_entry_clear_override_items", 1941, Parameter.MissionTemplateIdentifier),
                new Operator("mission_tpl_entry_add_override_item", 1942, Parameter.MissionTemplateIdentifier, Parameter.None, Parameter.ItemIdentifier),
                new Operator("set_current_color", 1950),
                new Operator("set_position_delta", 1955),
                new Operator("add_point_light", 1960),
                new Operator("particle_system_add_new", 1965, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("particle_system_emit", 1968, Parameter.ParticleSystemIdentifier),
                new Operator("particle_system_burst", 1969, Parameter.ParticleSystemIdentifier, Parameter.Position),
                new Operator("set_spawn_position", 1970, Parameter.Position),
                new Operator("spawn_item", 1971, Parameter.ItemIdentifier, Parameter.ItemModifier),
                new Operator("spawn_agent", 1972, Parameter.TroopIdentifier),
                new Operator("spawn_horse", 1973, Parameter.ItemIdentifier),
                new Operator("cur_tableau_add_tableau_mesh", 1980, Parameter.TableauMaterialIdentifier, Parameter.None, Parameter.Position),
                new Operator("cur_item_set_tableau_material", 1981, Parameter.TableauMaterialIdentifier),
                new Operator("cur_scene_prop_set_tableau_material", 1982, Parameter.TableauMaterialIdentifier),
                new Operator("cur_map_icon_set_tableau_material", 1983, Parameter.TableauMaterialIdentifier),
                new Operator("cur_tableau_render_as_alpha_mask", 1984),
                new Operator("cur_tableau_set_background_color", 1985),
                new Operator("cur_tableau_set_ambient_light", 1987),
                new Operator("cur_tableau_set_camera_position", 1988, Parameter.Position),
                new Operator("cur_tableau_set_camera_parameters", 1989),
                new Operator("cur_tableau_add_point_light", 1990, Parameter.Position),
                new Operator("cur_tableau_add_sun_light", 1991, Parameter.Position),
                new Operator("cur_tableau_add_mesh", 1992, Parameter.MeshIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_mesh_with_vertex_color", 1993, Parameter.MeshIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_map_icon", 1994, Parameter.MapIconIdentifier, Parameter.Position),
                new Operator("cur_tableau_add_troop", 1995, Parameter.TroopIdentifier, Parameter.Position, Parameter.AnimationIdentifier),
                new Operator("cur_tableau_add_horse", 1996, Parameter.ItemIdentifier, Parameter.Position, Parameter.AnimationIdentifier),
                new Operator("cur_tableau_set_override_flags", 1997),
                new Operator("cur_tableau_clear_override_items", 1998),
                new Operator("cur_tableau_add_override_item", 1999, Parameter.ItemIdentifier),
                new Operator("cur_tableau_add_mesh_with_scale_and_vertex_color", 2000, Parameter.MeshIdentifier, Parameter.Position, Parameter.Position),
                new Operator("mission_cam_set_mode", 2001),
                new Operator("mission_get_time_speed", 2002),
                new Operator("mission_set_time_speed", 2003),
                new Operator("mission_time_speed_move_to_value", 2004),
                new Operator("mission_cam_get_position", 2010, Parameter.Position),
                new Operator("mission_cam_set_position", 2011, Parameter.Position),
                new Operator("mission_cam_animate_to_position", 2012, Parameter.Position),
                new Operator("mission_cam_get_aparture", 2013),
                new Operator("mission_cam_set_aparture", 2014),
                new Operator("mission_cam_animate_to_aparture", 2015),
                new Operator("mission_cam_animate_to_position_and_aparture", 2016, Parameter.Position),
                new Operator("mission_cam_set_target_agent", 2017),
                new Operator("mission_cam_clear_target_agent", 2018),
                new Operator("talk_info_show", 2020),
                new Operator("talk_info_set_relation_bar", 2021),
                new Operator("talk_info_set_line", 2022, Parameter.None, Parameter.String),
                new Operator("set_background_mesh", 2031, Parameter.MeshIdentifier),
                new Operator("set_game_menu_tableau_mesh", 2032, Parameter.TableauMaterialIdentifier, Parameter.None, Parameter.Position),
                new Operator("change_screen_return", 2040),
                new Operator("change_screen_loot", 2041, Parameter.TroopIdentifier),
                new Operator("change_screen_trade", 2042),
                new Operator("change_screen_exchange_members", 2043),
                new Operator("change_screen_trade_prisoners", 2044),
                new Operator("change_screen_buy_mercenaries", 2045),
                new Operator("change_screen_view_character", 2046),
                new Operator("change_screen_training", 2047),
                new Operator("change_screen_mission", 2048),
                new Operator("change_screen_map_conversation", 2049),
                new Operator("change_screen_exchange_with_party", 2050, Parameter.PartyIdentifier),
                new Operator("change_screen_equip_other", 2051, Parameter.TroopIdentifier),
                new Operator("change_screen_map", 2052),
                new Operator("change_screen_notes", 2053),
                new Operator("change_screen_quit", 2055),
                new Operator("change_screen_give_members", 2056),
                new Operator("jump_to_menu", 2060, Parameter.MenuIdentifier),
                new Operator("disable_menu_option", 2061),
                new Operator("store_trigger_param_1", 2071),
                new Operator("store_trigger_param_2", 2072),
                new Operator("set_trigger_result", 2075),
                new Operator("val_add", 2105),
                new Operator("val_sub", 2106),
                new Operator("val_mul", 2107),
                new Operator("val_div", 2108),
                new Operator("val_mod", 2109),
                new Operator("val_min", 2110),
                new Operator("val_max", 2111),
                new Operator("val_clamp", 2112),
                new Operator("val_abs", 2113),
                new Operator("val_or", 2114),
                new Operator("val_and", 2115),
                new Operator("store_or", 2116),
                new Operator("store_and", 2117),
                new Operator("store_mod", 2119),
                new Operator("store_add", 2120),
                new Operator("store_sub", 2121),
                new Operator("store_mul", 2122),
                new Operator("store_div", 2123),
                new Operator("set_fixed_point_multiplier", 2124),
                new Operator("store_sqrt", 2125),
                new Operator("store_pow", 2126),
                new Operator("store_sin", 2127),
                new Operator("store_cos", 2128),
                new Operator("store_tan", 2129),
                new Operator("convert_to_fixed_point", 2130),
                new Operator("convert_from_fixed_point", 2131),
                new Operator("assign", 2133),
                new Operator("shuffle_range", 2134),
                new Operator("store_random", 2135),
                new Operator("store_random_in_range", 2136),
                new Operator("store_troop_gold", 2149, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_num_free_stacks", 2154, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_num_free_prisoner_stacks", 2155, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_party_size", 2156, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_party_size_wo_prisoners", 2157, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_troop_kind_count", 2158),
                new Operator("store_num_regular_prisoners", 2159, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_troop_count_companions", 2160, Parameter.None, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("store_troop_count_prisoners", 2161, Parameter.None, Parameter.TroopIdentifier, Parameter.PartyIdentifier),
                new Operator("store_item_kind_count", 2165, Parameter.None, Parameter.ItemIdentifier, Parameter.TroopIdentifier),
                new Operator("store_free_inventory_capacity", 2167, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_skill_level", 2170, Parameter.None, Parameter.SkillIdentifier, Parameter.TroopIdentifier),
                new Operator("store_character_level", 2171, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_attribute_level", 2172, Parameter.None, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("store_troop_faction", 2173, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_troop_health", 2175, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_proficiency_level", 2176, Parameter.None, Parameter.TroopIdentifier, Parameter.AttributeIdentifier),
                new Operator("store_relation", 2190, Parameter.None, Parameter.FactionIdentifier, Parameter.FactionIdentifier),
                new Operator("store_conversation_agent", 2199),
                new Operator("store_conversation_troop", 2200),
                new Operator("store_partner_faction", 2201),
                new Operator("store_encountered_party", 2202),
                new Operator("store_encountered_party2", 2203),
                new Operator("store_faction_of_party", 2204),
                new Operator("store_current_scene", 2211),
                new Operator("store_item_value", 2230, Parameter.None, Parameter.ItemIdentifier),
                new Operator("store_troop_value", 2231, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_partner_quest", 2240),
                new Operator("store_random_quest_in_range", 2250),
                new Operator("store_random_troop_to_raise", 2251),
                new Operator("store_random_troop_to_capture", 2252),
                new Operator("store_random_party_in_range", 2254),
                new Operator("store01_random_parties_in_range", 2255),
                new Operator("store_random_horse", 2257),
                new Operator("store_random_equipment", 2258),
                new Operator("store_random_armor", 2259),
                new Operator("store_quest_number", 2261, Parameter.None, Parameter.QuestIdentifier),
                new Operator("store_quest_item", 2262, Parameter.None, Parameter.ItemIdentifier),
                new Operator("store_quest_troop", 2263, Parameter.None, Parameter.TroopIdentifier),
                new Operator("store_current_hours", 2270),
                new Operator("store_time_of_day", 2271),
                new Operator("store_current_day", 2272),
                new Operator("is_currently_night", 2273),
                new Operator("store_distance_to_party_from_party", 2281, Parameter.None, Parameter.PartyIdentifier, Parameter.PartyIdentifier),
                new Operator("get_party_ai_behavior", 2290, Parameter.None, Parameter.PartyIdentifier),
                new Operator("get_party_ai_object", 2291, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_get_ai_target_position", 2292, Parameter.Position, Parameter.PartyIdentifier),
                new Operator("get_party_ai_current_behavior", 2293, Parameter.None, Parameter.PartyIdentifier),
                new Operator("get_party_ai_current_object", 2294, Parameter.None, Parameter.PartyIdentifier),
                new Operator("store_num_parties_created", 2300, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_destroyed", 2301, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_destroyed_by_player", 2302, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_num_parties_of_template", 2310, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("store_random_party_of_template", 2311, Parameter.None, Parameter.PartyTemplateIdentifier),
                new Operator("str_clear", 2319, Parameter.String),
                new Operator("str_store_string", 2320, Parameter.String, Parameter.String),
                new Operator("str_store_string_reg", 2321, Parameter.String, Parameter.String),
                new Operator("str_store_troop_name", 2322, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_troop_name_plural", 2323, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_troop_name_by_count", 2324, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_item_name", 2325, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_item_name_plural", 2326, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_item_name_by_count", 2327, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_store_party_name", 2330, Parameter.String, Parameter.PartyIdentifier),
                new Operator("str_store_agent_name", 2332, Parameter.String),
                new Operator("str_store_faction_name", 2335, Parameter.String, Parameter.FactionIdentifier),
                new Operator("str_store_quest_name", 2336, Parameter.String, Parameter.QuestIdentifier),
                new Operator("str_store_date", 2340, Parameter.String),
                new Operator("str_store_troop_name_link", 2341, Parameter.String, Parameter.TroopIdentifier),
                new Operator("str_store_party_name_link", 2342, Parameter.String, Parameter.PartyIdentifier),
                new Operator("str_store_faction_name_link", 2343, Parameter.String, Parameter.FactionIdentifier),
                new Operator("str_store_quest_name_link", 2344, Parameter.String, Parameter.FactionIdentifier),
                new Operator("store_remaining_team_no", 2360),
                new Operator("store_mission_timer_a", 2370),
                new Operator("store_mission_timer_b", 2371),
                new Operator("store_mission_timer_c", 2372),
                new Operator("reset_mission_timer_a", 2375),
                new Operator("reset_mission_timer_b", 2376),
                new Operator("reset_mission_timer_c", 2377),
                new Operator("store_enemy_count", 2380),
                new Operator("store_friend_count", 2381),
                new Operator("store_ally_count", 2382),
                new Operator("store_defender_count", 2383),
                new Operator("store_attacker_count", 2384),
                new Operator("store_normalized_team_count", 2385)
            };
        }
    }
}
