using System.Collections.Generic;

namespace Decomp.Core.Operators
{
    //real version: 4.6.1
    public class WarbandScriptEnhancer450Version : IGameVersion
    {
        public IEnumerable<Operator> GetOperators()
        {
            return new List<Operator>
            {
                new Operator("break_loop", 8),
                new Operator("continue_loop", 9),
                new Operator("try_for_dict_keys", 18, Parameter.String),
                new Operator("server_set_max_num_players", 491),
                new Operator("position_rotate_x", 723, Parameter.Position),
                new Operator("position_rotate_y", 724, Parameter.Position),
                new Operator("position_rotate_z", 725, Parameter.Position),
                new Operator("position_rotate_z_floating", 734, Parameter.Position),
                new Operator("position_rotate_x_floating", 738, Parameter.Position),
                new Operator("position_rotate_y_floating", 739, Parameter.Position),
                new Operator("is_vanilla_warband", 1004),
                new Operator("prop_instance_receive_damage", 1877, Parameter.ScenePropIdentifier),
                new Operator("val_shr", 2800),
                new Operator("store_shr", 2801),
                new Operator("val_lshr", 2802),
                new Operator("store_lshr", 2803),
                new Operator("val_shl", 2804),
                new Operator("store_shl", 2805),
                new Operator("val_xor", 2806),
                new Operator("store_xor", 2807),
                new Operator("val_not", 2808),
                new Operator("store_not", 2809),
                new Operator("player_set_skin", 2900),
                new Operator("player_stop_controlling_agent", 2901),
                new Operator("player_set_banner_id", 2902),
                new Operator("player_set_username", 2903, Parameter.None, Parameter.String),
                new Operator("player_temp_ban", 2904),
                new Operator("register_get", 3000),
                new Operator("register_set", 3001),
                new Operator("store_wse_version", 3002),
                new Operator("item_slot_gt", 3003, Parameter.ItemIdentifier),
                new Operator("party_template_slot_gt", 3004),
                new Operator("troop_slot_gt", 3005, Parameter.TroopIdentifier),
                new Operator("faction_slot_gt", 3006, Parameter.FactionIdentifier),
                new Operator("quest_slot_gt", 3007, Parameter.QuestIdentifier),
                new Operator("scene_slot_gt", 3008),
                new Operator("party_slot_gt", 3009, Parameter.PartyIdentifier),
                new Operator("player_slot_gt", 3010),
                new Operator("team_slot_gt", 3011),
                new Operator("agent_slot_gt", 3012),
                new Operator("scene_prop_slot_gt", 3013, Parameter.ScenePropIdentifier),
                new Operator("store_current_trigger", 3014),
                new Operator("return_values", 3015),
                new Operator("store_num_return_values", 3016),
                new Operator("store_return_value", 3017),
                new Operator("set_forced_lod", 3018),
                new Operator("send_message_to_url_advanced", 3019, Parameter.String, Parameter.String),
                new Operator("mtsrand", 3020),
                new Operator("mtrand", 3021),
                new Operator("get_time", 3022),
                new Operator("order_flag_is_active", 3023),
                new Operator("play_bink_file", 3024),
                new Operator("process_advanced_url_messages", 3025),
                new Operator("sleep_ms", 3026),
                new Operator("timer_reset", 3027),
                new Operator("timer_get_elapsed_time", 3028),
                new Operator("shell_open_url", 3029),
                new Operator("set_main_party", 3030, Parameter.PartyIdentifier),
                new Operator("get_main_party", 3031),
                new Operator("make_screenshot", 3032, Parameter.None, Parameter.String),
                new Operator("send_post_message_to_url_advanced", 3033, Parameter.String, Parameter.String),
                new Operator("game_key_get_key", 3100, Parameter.None, Parameter.GameKeyCode),
                new Operator("key_released", 3101, Parameter.KeyCode),
                new Operator("game_key_released", 3102, Parameter.GameKeyCode),
                new Operator("dict_create", 3200),
                new Operator("dict_free", 3201),
                new Operator("dict_load_file", 3202),
                new Operator("dict_load_dict", 3203),
                new Operator("dict_save", 3204),
                new Operator("dict_clear", 3205),
                new Operator("dict_is_empty", 3206),
                new Operator("dict_has_key", 3207, Parameter.None, Parameter.KeyCode),
                new Operator("dict_get_size", 3208),
                new Operator("dict_delete_file", 3209),
                new Operator("dict_get_str", 3210, Parameter.String, Parameter.None, Parameter.KeyCode),
                new Operator("dict_get_int", 3211, Parameter.None, Parameter.None, Parameter.KeyCode),
                new Operator("dict_set_str", 3212, Parameter.None, Parameter.KeyCode, Parameter.String),
                new Operator("dict_set_int", 3213, Parameter.None, Parameter.KeyCode),
                new Operator("dict_get_key_by_iterator", 3214, Parameter.String),
                new Operator("dict_get_pos", 3215, Parameter.Position, Parameter.None, Parameter.KeyCode, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("dict_set_pos", 3216, Parameter.None, Parameter.KeyCode, Parameter.Position),
                new Operator("dict_load_file_json", 3217),
                new Operator("dict_save_json", 3218),
                new Operator("dict_from_url_encoded_json", 3219, Parameter.None, Parameter.String),
                new Operator("dict_to_url_encoded_json", 3220, Parameter.String),
                new Operator("dict_erase", 3221, Parameter.None, Parameter.KeyCode),
                new Operator("agent_get_item_modifier", 3300),
                new Operator("agent_get_item_slot_modifier", 3301, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_animation_progress", 3302),
                new Operator("agent_get_dna", 3303),
                new Operator("agent_get_ground_scene_prop", 3304),
                new Operator("agent_set_item_slot_ammo", 3305, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_item_slot_hit_points", 3306, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_set_item_slot_hit_points", 3307, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_wielded_item_slot_no", 3308),
                new Operator("agent_get_scale", 3309),
                new Operator("agent_set_forced_lod", 3310),
                new Operator("agent_get_item_slot_flags", 3311, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_ai_get_move_target_position", 3312, Parameter.Position),
                new Operator("agent_set_horse", 3313),
                new Operator("agent_ai_set_simple_behavior", 3314),
                new Operator("agent_accelerate", 3315, Parameter.None, Parameter.Position),
                new Operator("agent_set_item_slot_modifier", 3316, Parameter.None, Parameter.InventorySlot, Parameter.ItemModifier),
                new Operator("agent_body_meta_mesh_set_vertex_keys_time_point", 3317),
                new Operator("agent_body_meta_mesh_set_visibility", 3318),
                new Operator("agent_set_personal_animation", 3319, Parameter.None, Parameter.AnimationIdentifier, Parameter.AnimationIdentifier),
                new Operator("agent_get_personal_animation", 3320, Parameter.None, Parameter.None, Parameter.AnimationIdentifier),
                new Operator("agent_set_default_animations", 3321),
                new Operator("agent_cancel_current_animation", 3322),
                new Operator("agent_get_ranged_damage_modifier", 3323),
                new Operator("multiplayer_send_chat_message_to_player", 3400),
                new Operator("multiplayer_send_composite_message_to_player", 3401),
                new Operator("multiplayer_send_composite_message_to_server", 3402),
                new Operator("multiplayer_get_cur_profile", 3403),
                new Operator("multiplayer_get_num_profiles", 3404),
                new Operator("multiplayer_message_init", 3405),
                new Operator("multiplayer_message_put_string", 3406, Parameter.None, Parameter.String, Parameter.String),
                new Operator("multiplayer_message_put_int", 3407),
                new Operator("multiplayer_message_put_position", 3408, Parameter.None, Parameter.Position, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("multiplayer_message_put_coordinate", 3409, Parameter.None, Parameter.Position, Parameter.None, Parameter.None, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("multiplayer_cur_message_get_string", 3410, Parameter.String, Parameter.String),
                new Operator("multiplayer_cur_message_get_int", 3411),
                new Operator("multiplayer_cur_message_get_position", 3412, Parameter.Position, Parameter.None, Parameter.Position),
                new Operator("multiplayer_cur_message_get_coordinate", 3413, Parameter.Position, Parameter.None, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("multiplayer_cur_profile_get_skin", 3414),
                new Operator("server_set_password_admin", 3500),
                new Operator("server_set_password_private", 3501),
                new Operator("server_map_rotation_get_count", 3502),
                new Operator("server_map_rotation_get_index", 3503),
                new Operator("server_map_rotation_set_index", 3504),
                new Operator("server_map_rotation_get_map", 3505),
                new Operator("server_map_rotation_add_map", 3506),
                new Operator("server_map_rotation_remove_map", 3507),
                new Operator("server_get_horse_friendly_fire", 3508),
                new Operator("server_set_horse_friendly_fire", 3509),
                new Operator("server_get_show_crosshair", 3510),
                new Operator("server_set_show_crosshair", 3511),
                new Operator("get_server_option_at_connect", 3512),
                new Operator("server_set_password_rcon", 3513),
                new Operator("execute_server_console_command", 3514, Parameter.String),
                new Operator("store_cur_mission_template_no", 3600),
                new Operator("set_show_use_tooltip", 3601, Parameter.ToolTip),
                new Operator("set_ally_collision_threshold", 3602),
                new Operator("particle_system_remove", 3603),
                new Operator("get_spectated_agent_no", 3604),
                new Operator("prop_instance_set_forced_lod", 3605, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_variation_id", 3606, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_variation_id_2", 3607, Parameter.ScenePropIdentifier),
                new Operator("stop_time", 3608),
                new Operator("missile_get_path_point_position", 3609, Parameter.Position, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("get_water_level", 3610),
                new Operator("missile_remove_on_hit", 3611),
                new Operator("missile_is_valid", 3612),
                new Operator("missile_get_cur_position", 3613, Parameter.Position),
                new Operator("set_prop_collision_threshold", 3614),
                new Operator("troop_get_skill_points", 3700, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_skill_points", 3701, Parameter.TroopIdentifier),
                new Operator("troop_get_attribute_points", 3702, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_attribute_points", 3703, Parameter.TroopIdentifier),
                new Operator("troop_get_proficiency_points", 3704, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_proficiency_points", 3705, Parameter.TroopIdentifier),
                new Operator("troop_has_flag", 3706, Parameter.TroopIdentifier, Parameter.TroopFlags),
                new Operator("troop_set_skill", 3707, Parameter.TroopIdentifier, Parameter.SkillIdentifier),
                new Operator("troop_set_attribute", 3708, Parameter.TroopIdentifier),
                new Operator("troop_set_proficiency", 3709, Parameter.TroopIdentifier),
                new Operator("item_set_thrust_damage", 3800, Parameter.ItemIdentifier),
                new Operator("item_set_thrust_damage_type", 3801, Parameter.ItemIdentifier),
                new Operator("item_set_swing_damage", 3802, Parameter.ItemIdentifier),
                new Operator("item_set_swing_damage_type", 3803, Parameter.ItemIdentifier),
                new Operator("item_set_head_armor", 3804, Parameter.ItemIdentifier),
                new Operator("item_set_body_armor", 3805, Parameter.ItemIdentifier),
                new Operator("item_set_leg_armor", 3806, Parameter.ItemIdentifier),
                new Operator("item_set_speed_rating", 3807, Parameter.ItemIdentifier),
                new Operator("item_set_missile_speed", 3808, Parameter.ItemIdentifier),
                new Operator("item_set_horse_blood_particles", 3809, Parameter.ItemIdentifier),
                new Operator("party_stack_get_experience", 3900, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_num_upgradeable", 3901, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_has_flag", 3902, Parameter.PartyIdentifier, Parameter.PartyFlags),
                new Operator("party_heal_members", 3903, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("position_get_vector_to_position", 4100, Parameter.None, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_align_to_ground", 4101, Parameter.Position, Parameter.None, Parameter.None, Parameter.Position),
                new Operator("str_equals", 4200, Parameter.String, Parameter.String),
                new Operator("str_contains", 4201, Parameter.String, Parameter.String),
                new Operator("str_starts_with", 4202, Parameter.String, Parameter.String),
                new Operator("str_ends_with", 4203, Parameter.String, Parameter.String),
                new Operator("str_is_alpha", 4204, Parameter.String),
                new Operator("str_is_digit", 4205, Parameter.String),
                new Operator("str_is_whitespace", 4206, Parameter.String),
                new Operator("str_length", 4207, Parameter.None, Parameter.String),
                new Operator("str_index_of", 4208, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_last_index_of", 4209, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_get_char", 4210, Parameter.None, Parameter.String),
                new Operator("str_to_num", 4211, Parameter.None, Parameter.String),
                new Operator("str_compare", 4212, Parameter.None, Parameter.String, Parameter.String, Parameter.None, Parameter.String),
                new Operator("str_split", 4213, Parameter.None, Parameter.String, Parameter.String, Parameter.None, Parameter.None, Parameter.None, Parameter.String, Parameter.String, Parameter.String, Parameter.String),
                new Operator("str_sort", 4214, Parameter.String),
                new Operator("str_store_lower", 4215, Parameter.String, Parameter.String),
                new Operator("str_store_upper", 4216, Parameter.String, Parameter.String),
                new Operator("str_store_trim", 4217, Parameter.String, Parameter.String, Parameter.None, Parameter.String),
                new Operator("str_store_replace", 4218, Parameter.String, Parameter.String, Parameter.String, Parameter.String),
                new Operator("str_store_md5", 4219, Parameter.String, Parameter.String),
                new Operator("str_store_substring", 4220, Parameter.String, Parameter.String),
                new Operator("str_store_reverse", 4221, Parameter.String, Parameter.String),
                new Operator("str_store_join", 4222, Parameter.String, Parameter.String, Parameter.None, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_store_replace_spaces_with_underscores", 4223, Parameter.String, Parameter.String),
                new Operator("str_store_replace_underscores_with_spaces", 4224, Parameter.String, Parameter.String),
                new Operator("str_store_multiplayer_profile_name", 4225, Parameter.String),
                new Operator("str_store_module_setting", 4226, Parameter.String, Parameter.None, Parameter.String),
                new Operator("str_store_server_password_admin", 4227, Parameter.String),
                new Operator("str_store_server_password_private", 4228, Parameter.String),
                new Operator("str_store_overlay_text", 4229, Parameter.String),
                new Operator("str_store_player_ip", 4230, Parameter.String, Parameter.None, Parameter.String),
                new Operator("str_store_game_variable", 4231, Parameter.String, Parameter.None, Parameter.String),
                new Operator("str_store_skill_name", 4232, Parameter.String, Parameter.SkillIdentifier),
                new Operator("str_store_float", 4233, Parameter.String, Parameter.FloatRegister),
                new Operator("str_sanitize", 4234, Parameter.String),
                new Operator("str_store_item_id", 4235, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_is_integer", 4236, Parameter.String),
                new Operator("str_store_multiplayer_profile_face_keys", 4237, Parameter.String),
                new Operator("str_store_server_password_rcon", 4238, Parameter.String),
                new Operator("str_store_item_mesh_name", 4239, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_regex_match", 4240, Parameter.String, Parameter.String),
                new Operator("str_regex_search", 4241, Parameter.String, Parameter.String),
                new Operator("str_regex_get_matches", 4242, Parameter.None, Parameter.String, Parameter.String, Parameter.String, Parameter.None, Parameter.String, Parameter.String, Parameter.String),
                new Operator("str_store_regex_replace", 4243, Parameter.String, Parameter.String, Parameter.String, Parameter.String),
                new Operator("str_decode_url", 4244, Parameter.String, Parameter.String, Parameter.String),
                new Operator("options_get_verbose_casualties", 4300),
                new Operator("options_set_verbose_casualties", 4301),
                new Operator("options_set_cheat_mode", 4303),
                new Operator("options_get_cheat_mode", 4302),
                new Operator("options_get_realistic_headshots", 4304),
                new Operator("options_set_realistic_headshots", 4305),
                new Operator("fld", 4400, Parameter.FloatRegister),
                new Operator("fld_str", 4401, Parameter.FloatRegister, Parameter.String),
                new Operator("fld_pos_x", 4402, Parameter.FloatRegister, Parameter.Position),
                new Operator("fld_pos_y", 4403, Parameter.FloatRegister, Parameter.Position),
                new Operator("fld_pos_z", 4404, Parameter.FloatRegister, Parameter.Position),
                new Operator("fst", 4405, Parameter.None, Parameter.FloatRegister),
                new Operator("fcpy", 4406, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("feq", 4407, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fgt", 4408, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("flt", 4409, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fge", 4410, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fle", 4411, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsub", 4412, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmul", 4413, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fdiv", 4414, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmin", 4415, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmax", 4416, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fclamp", 4417, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsqrt", 4418, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fabs", 4419, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fceil", 4420, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ffloor", 4421, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fexp", 4422, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fpow", 4423, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fln", 4424, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("flog", 4425, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmod", 4426, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsin", 4427, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fcos", 4428, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ftan", 4429, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsinh", 4430, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fcosh", 4431, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ftanh", 4432, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fasin", 4433, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("facos", 4434, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fatan", 4435, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fatan2", 4436, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("feval", 4437, Parameter.String),
                new Operator("fadd", 4438, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("scene_set_flags", 4500, Parameter.SceneIdentifier, Parameter.SceneFlags),
                new Operator("scene_set_water_level", 4501, Parameter.SceneIdentifier),
                new Operator("scene_set_bounds", 4502, Parameter.SceneIdentifier),
                new Operator("scene_set_outer_terrain", 4503, Parameter.SceneIdentifier, Parameter.String),
                new Operator("scene_set_terrain_seed", 4504, Parameter.SceneIdentifier),
                new Operator("scene_set_river_seed", 4505, Parameter.SceneIdentifier),
                new Operator("scene_set_flora_seed", 4506, Parameter.SceneIdentifier),
                new Operator("scene_set_deep_water", 4507, Parameter.SceneIdentifier),
                new Operator("scene_set_place_river", 4508, Parameter.SceneIdentifier),
                new Operator("scene_set_disable_grass", 4509, Parameter.SceneIdentifier),
                new Operator("scene_set_valley_size", 4510, Parameter.SceneIdentifier),
                new Operator("scene_set_hill_height", 4511, Parameter.SceneIdentifier),
                new Operator("scene_set_ruggedness", 4512, Parameter.SceneIdentifier),
                new Operator("scene_set_vegetation", 4513, Parameter.SceneIdentifier),
                new Operator("scene_set_size", 4514, Parameter.SceneIdentifier),
                new Operator("scene_set_region_type", 4515, Parameter.SceneIdentifier),
                new Operator("scene_set_region_detail", 4516, Parameter.SceneIdentifier),
                new Operator("edit_mode_get_num_selected_prop_instances", 4600),
                new Operator("edit_mode_get_selected_prop_instance", 4601),
                new Operator("edit_mode_select_prop_instance", 4602, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_deselect_prop_instance", 4603, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_get_highlighted_prop_instance", 4604),
                new Operator("edit_mode_set_highlighted_prop_instance", 4605, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_set_enabled", 4606),
                new Operator("update_material", 4700, Parameter.String, Parameter.String),
                new Operator("menu_create_new", 4800, Parameter.None, Parameter.None, Parameter.String, Parameter.MenuFlags, Parameter.ScriptIdentifier),
                new Operator("menu_add_item", 4801, Parameter.MenuIdentifier),
                new Operator("menu_clear_items", 4802, Parameter.MenuIdentifier),
                new Operator("menu_clear_generated", 4803),
                new Operator("overlay_get_val", 4900),
                new Operator("presentation_activate", 4901, Parameter.PresentationIdentifier),
                new Operator("array_create", 5000),
                new Operator("array_free", 5001),
                new Operator("array_copy", 5002),
                new Operator("array_save_file", 5003),
                new Operator("array_load_file", 5004),
                new Operator("array_delete_file", 5005),
                new Operator("array_set_val", 5006),
                new Operator("array_set_val_all", 5007),
                new Operator("array_get_val", 5008),
                new Operator("array_push", 5009),
                new Operator("array_pop", 5010),
                new Operator("array_resize_dim", 5011),
                new Operator("array_get_dim_size", 5012),
                new Operator("array_get_dim_count", 5013),
                new Operator("array_get_type_id", 5014),
                new Operator("array_sort", 5015, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.None, Parameter.String),
                new Operator("array_sort_custom", 5016),
                new Operator("array_eq", 5017),
                new Operator("array_neq", 5018),
                new Operator("array_gt", 5019),
                new Operator("array_ge", 5020),
                new Operator("array_lt", 5021),
                new Operator("array_le", 5022),
                new Operator("lua_get_top", 5100),
                new Operator("lua_set_top", 5101),
                new Operator("lua_insert", 5102),
                new Operator("lua_remove", 5103),
                new Operator("lua_pop", 5104),
                new Operator("lua_to_int", 5105),
                new Operator("lua_to_str", 5106, Parameter.String),
                new Operator("lua_to_pos", 5107),
                new Operator("lua_push_int", 5108),
                new Operator("lua_push_str", 5109, Parameter.String),
                new Operator("lua_push_pos", 5110),
                new Operator("lua_get_type", 5111),
                new Operator("lua_call", 5112, Parameter.String),
                new Operator("lua_triggerCallback", 5113),

            };
        }
    }
}
