using System.Collections.Generic;

namespace Decomp.Core.Operators
{
    public class WarbandScriptEnhancer320Version : IGameVersion
    {
        public IEnumerable<Operator> GetOperators()
        {
            return new List<Operator>
            {
                new Operator("go_to", 0),
                new Operator("break_loop", 8),
                new Operator("continue_loop", 9),
                new Operator("try_for_agents", 12, Parameter.None, Parameter.Position),
                new Operator("try_for_attached_parties", 15, Parameter.None, Parameter.PartyIdentifier),
                new Operator("try_for_active_players", 16),
                new Operator("try_for_prop_instances", 17),
                new Operator("try_for_dict_keys", 18, Parameter.String),
                new Operator("server_set_max_num_players", 491),
                new Operator("position_rotate_x", 723, Parameter.Position),
                new Operator("position_rotate_y", 724, Parameter.Position),
                new Operator("position_rotate_z", 725, Parameter.Position),
                new Operator("position_rotate_x_floating", 738, Parameter.Position),
                new Operator("position_rotate_y_floating", 739, Parameter.Position),
                new Operator("is_vanilla_warband", 1004),
                new Operator("prop_instance_receive_damage", 1877, Parameter.ScenePropIdentifier),
                new Operator("store_trigger_param", 2070),
                new Operator("str_equals", 2600, Parameter.String, Parameter.String),
                new Operator("str_contains", 2601, Parameter.String, Parameter.String),
                new Operator("str_starts_with", 2602, Parameter.String, Parameter.String),
                new Operator("str_ends_with", 2603, Parameter.String, Parameter.String),
                new Operator("str_is_alpha", 2604, Parameter.String),
                new Operator("str_is_digit", 2605, Parameter.String),
                new Operator("str_is_whitespace", 2606, Parameter.String),
                new Operator("str_length", 2607, Parameter.None, Parameter.String),
                new Operator("str_index_of", 2608, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_last_index_of", 2609, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_get_char", 2610, Parameter.None, Parameter.String),
                new Operator("str_to_num", 2611, Parameter.None, Parameter.String),
                new Operator("str_compare", 2612, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_split", 2613, Parameter.None, Parameter.String, Parameter.String),
                new Operator("str_sort", 2614, Parameter.String),
                new Operator("str_store_lower", 2615, Parameter.String, Parameter.String),
                new Operator("str_store_upper", 2616, Parameter.String, Parameter.String),
                new Operator("str_store_trim", 2617, Parameter.String, Parameter.String),
                new Operator("str_store_replace", 2618, Parameter.String, Parameter.String, Parameter.String, Parameter.String),
                new Operator("str_store_md5", 2619, Parameter.String, Parameter.String),
                new Operator("str_store_substring", 2620, Parameter.String, Parameter.String),
                new Operator("str_store_reverse", 2621, Parameter.String, Parameter.String),
                new Operator("str_store_join", 2622, Parameter.String, Parameter.String),
                new Operator("str_store_replace_spaces_with_underscores", 2623, Parameter.String, Parameter.String),
                new Operator("str_store_replace_underscores_with_spaces", 2624, Parameter.String, Parameter.String),
                new Operator("str_store_multiplayer_profile_name", 2625, Parameter.String),
                new Operator("str_store_face_keys", 2626, Parameter.String, Parameter.FaceKeyRegister),
                new Operator("str_store_module_setting", 2627, Parameter.String),
                new Operator("str_store_server_password_admin", 2628, Parameter.String),
                new Operator("str_store_server_password_private", 2629, Parameter.String),
                new Operator("str_store_overlay_text", 2630, Parameter.String),
                new Operator("str_store_player_ip", 2631, Parameter.String),
                new Operator("str_store_game_variable", 2632, Parameter.String),
                new Operator("str_store_skill_name", 2633, Parameter.String),
                new Operator("str_store_float", 2634, Parameter.String, Parameter.FloatRegister),
                new Operator("str_sanitize", 2635, Parameter.String),
                new Operator("str_store_item_id", 2636, Parameter.String, Parameter.ItemIdentifier),
                new Operator("str_is_integer", 2637, Parameter.String),
                new Operator("face_keys_init", 2700, Parameter.FaceKeyRegister),
                new Operator("face_keys_copy", 2701, Parameter.FaceKeyRegister, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_hair", 2702, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_hair", 2703, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_beard", 2704, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_beard", 2705, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_face_texture", 2706, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_face_texture", 2707, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_hair_texture", 2708, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_hair_texture", 2709, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_hair_color", 2710, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_hair_color", 2711, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_age", 2712, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_age", 2713, Parameter.FaceKeyRegister),
                new Operator("face_keys_get_morph_key", 2714, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("face_keys_set_morph_key", 2715, Parameter.FaceKeyRegister),
                new Operator("face_keys_store_string", 2716, Parameter.FaceKeyRegister, Parameter.String),
                new Operator("val_shr", 2800),
                new Operator("store_shr", 2801),
                new Operator("val_lshr", 2802),
                new Operator("store_lshr", 2803),
                new Operator("val_shl", 2804),
                new Operator("store_shl", 2805),
                new Operator("val_xor", 2806),
                new Operator("store_xor", 2807),
                new Operator("val_not", 2808),
                new Operator("store_not", 2809),
                new Operator("player_get_face_keys", 2900, Parameter.FaceKeyRegister),
                new Operator("player_set_face_keys", 2901, Parameter.None, Parameter.FaceKeyRegister),
                new Operator("player_set_skin", 2902),
                new Operator("player_stop_controlling_agent", 2903),
                new Operator("player_set_banner_id", 2904),
                new Operator("register_get", 3000),
                new Operator("register_set", 3001),
                new Operator("store_wse_version", 3002),
                new Operator("item_slot_gt", 3003, Parameter.ItemIdentifier),
                new Operator("party_template_slot_gt", 3004, Parameter.PartyTemplateIdentifier),
                new Operator("troop_slot_gt", 3005, Parameter.TroopIdentifier),
                new Operator("faction_slot_gt", 3006, Parameter.FactionIdentifier),
                new Operator("quest_slot_gt", 3007, Parameter.QuestIdentifier),
                new Operator("scene_slot_gt", 3008),
                new Operator("party_slot_gt", 3009, Parameter.PartyIdentifier),
                new Operator("player_slot_gt", 3010),
                new Operator("team_slot_gt", 3011),
                new Operator("agent_slot_gt", 3012),
                new Operator("scene_prop_slot_gt", 3013, Parameter.ScenePropIdentifier),
                new Operator("store_current_trigger", 3014),
                new Operator("return_values", 3015),
                new Operator("store_num_return_values", 3016),
                new Operator("store_return_value", 3017),
                new Operator("set_forced_lod", 3018),
                new Operator("send_message_to_url_advanced", 3019, Parameter.String, Parameter.String),
                new Operator("mtsrand", 3020),
                new Operator("mtrand", 3021),
                new Operator("get_time", 3022),
                new Operator("close_order_menu", 3023),
                new Operator("order_flag_is_active", 3024),
                new Operator("play_bink_file", 3025),
                new Operator("process_advanced_url_messages", 3026),
                new Operator("sleep_ms", 3027),
                new Operator("timer_reset", 3028),
                new Operator("timer_get_elapsed_time", 3029),
                new Operator("game_key_get_key", 3100, Parameter.None, Parameter.GameKeyCode),
                new Operator("key_released", 3101, Parameter.KeyCode),
                new Operator("game_key_released", 3102, Parameter.GameKeyCode),
                new Operator("dict_create", 3200),
                new Operator("dict_free", 3201),
                new Operator("dict_load_file", 3202),
                new Operator("dict_load_dict", 3203),
                new Operator("dict_save", 3204),
                new Operator("dict_clear", 3205),
                new Operator("dict_is_empty", 3206),
                new Operator("dict_has_key", 3207, Parameter.None),
                new Operator("dict_get_size", 3208),
                new Operator("dict_delete_file", 3209),
                new Operator("dict_get_str", 3210, Parameter.String, Parameter.None, Parameter.None),
                new Operator("dict_get_int", 3211, Parameter.None, Parameter.None, Parameter.None),
                new Operator("dict_set_str", 3212, Parameter.None, Parameter.None, Parameter.String),
                new Operator("dict_set_int", 3213, Parameter.None, Parameter.None),
                new Operator("agent_get_item_modifier", 3300),
                new Operator("agent_get_item_slot_modifier", 3301, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_animation_progress", 3302),
                new Operator("agent_get_dna", 3303),
                new Operator("agent_get_ground_scene_prop", 3304),
                new Operator("agent_get_item_slot_ammo", 3305, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_set_item_slot_ammo", 3306, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_item_slot_hit_points", 3307, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_set_item_slot_hit_points", 3308, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_get_wielded_item_slot_no", 3309),
                new Operator("agent_get_bone_position", 3310, Parameter.Position),
                new Operator("agent_get_scale", 3311),
                new Operator("agent_set_forced_lod", 3312),
                new Operator("agent_get_item_slot_flags", 3313, Parameter.None, Parameter.None, Parameter.InventorySlot),
                new Operator("agent_ai_get_move_target_position", 3314, Parameter.Position),
                new Operator("agent_set_horse", 3315),
                new Operator("agent_ai_set_simple_behavior", 3316),
                new Operator("agent_accelerate", 3317, Parameter.None, Parameter.Position),
                new Operator("agent_set_item_slot_modifier", 3318, Parameter.None, Parameter.InventorySlot),
                new Operator("multiplayer_send_chat_message_to_player", 3400),
                new Operator("multiplayer_send_composite_message_to_player", 3401),
                new Operator("multiplayer_send_composite_message_to_server", 3402),
                new Operator("multiplayer_get_cur_profile", 3403),
                new Operator("multiplayer_get_num_profiles", 3404),
                new Operator("multiplayer_profile_get_face_keys", 3405, Parameter.FaceKeyRegister),
                new Operator("multiplayer_message_init", 3406),
                new Operator("multiplayer_message_put_string", 3407, Parameter.None, Parameter.String),
                new Operator("multiplayer_message_put_int", 3408),
                new Operator("multiplayer_message_put_position", 3409, Parameter.None, Parameter.Position),
                new Operator("multiplayer_message_put_coordinate", 3410, Parameter.None, Parameter.Position),
                new Operator("multiplayer_message_put_face_keys", 3411),
                new Operator("multiplayer_cur_message_get_string", 3412, Parameter.String),
                new Operator("multiplayer_cur_message_get_int", 3413),
                new Operator("multiplayer_cur_message_get_position", 3414, Parameter.Position),
                new Operator("multiplayer_cur_message_get_coordinate", 3415, Parameter.Position),
                new Operator("multiplayer_cur_message_get_face_keys", 3416),
                new Operator("server_set_password_admin", 3500),
                new Operator("server_set_password_private", 3501),
                new Operator("server_map_rotation_get_count", 3502),
                new Operator("server_map_rotation_get_index", 3503),
                new Operator("server_map_rotation_set_index", 3504),
                new Operator("server_map_rotation_get_map", 3505),
                new Operator("server_map_rotation_add_map", 3506),
                new Operator("server_map_rotation_remove_map", 3507),
                new Operator("server_get_horse_friendly_fire", 3508),
                new Operator("server_set_horse_friendly_fire", 3509),
                new Operator("server_get_show_crosshair", 3510),
                new Operator("server_set_show_crosshair", 3511),
                new Operator("get_server_option_at_connect", 3512),
                new Operator("store_cur_mission_template_no", 3600),
                new Operator("prop_instance_clear_attached_missiles", 3601, Parameter.ScenePropIdentifier),
                new Operator("camera_in_first_person", 3602),
                new Operator("set_camera_in_first_person", 3603),
                new Operator("set_show_use_tooltip", 3604, Parameter.Tooltip),
                new Operator("set_ally_collision_threshold", 3605),
                new Operator("set_prop_collision_threshold", 3606),
                new Operator("particle_system_remove", 3607),
                new Operator("get_camera_position", 3608, Parameter.Position),
                new Operator("get_spectated_agent_no", 3609),
                new Operator("prop_instance_set_forced_lod", 3610, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_variation_id", 3611, Parameter.ScenePropIdentifier),
                new Operator("prop_instance_set_variation_id_2", 3612, Parameter.ScenePropIdentifier),
                new Operator("stop_time", 3613),
                new Operator("cur_missile_get_path_point_position", 3614, Parameter.Position),
                new Operator("get_water_level", 3615),
                new Operator("cast_ray", 3616, Parameter.None, Parameter.Position, Parameter.Position),
                new Operator("prop_instance_set_vertex_keys_time_point", 3617, Parameter.ScenePropIdentifier),
                new Operator("missile_remove_on_hit", 3618),
                new Operator("troop_get_skill_points", 3700, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_skill_points", 3701, Parameter.TroopIdentifier),
                new Operator("troop_get_attribute_points", 3702, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_attribute_points", 3703, Parameter.TroopIdentifier),
                new Operator("troop_get_proficiency_points", 3704, Parameter.None, Parameter.TroopIdentifier),
                new Operator("troop_set_proficiency_points", 3705, Parameter.TroopIdentifier),
                new Operator("troop_get_face_keys", 3706, Parameter.FaceKeyRegister, Parameter.TroopIdentifier),
                new Operator("troop_set_face_keys", 3707, Parameter.TroopIdentifier, Parameter.FaceKeyRegister),
                new Operator("troop_has_flag", 3708, Parameter.TroopIdentifier, Parameter.TroopFlags),
                new Operator("troop_set_skill", 3709, Parameter.TroopIdentifier),
                new Operator("troop_set_attribute", 3710, Parameter.TroopIdentifier),
                new Operator("troop_set_proficiency", 3711, Parameter.TroopIdentifier, Parameter.WeaponProficiency),
                new Operator("item_get_weight", 3800, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_value", 3801, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_difficulty", 3802, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_head_armor", 3803, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_body_armor", 3804, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_leg_armor", 3805, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_hit_points", 3806, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_weapon_length", 3807, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_speed_rating", 3808, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_missile_speed", 3809, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_max_ammo", 3810, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_accuracy", 3811, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_shield_width", 3812, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_shield_height", 3813, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_scale", 3814, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_speed", 3815, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_maneuver", 3816, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_food_quality", 3817, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_abundance", 3818, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_thrust_damage", 3819, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_thrust_damage_type", 3820, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_swing_damage", 3821, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_swing_damage_type", 3822, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_get_horse_charge_damage", 3823, Parameter.None, Parameter.ItemIdentifier),
                new Operator("item_has_property", 3824, Parameter.ItemIdentifier, Parameter.ItemProperty),
                new Operator("item_has_capability", 3825, Parameter.ItemIdentifier, Parameter.ItemCapability),
                new Operator("item_has_modifier", 3826, Parameter.ItemIdentifier),
                new Operator("item_has_faction", 3827, Parameter.ItemIdentifier, Parameter.FactionIdentifier),
                new Operator("item_set_thrust_damage", 3828, Parameter.ItemIdentifier),
                new Operator("item_set_thrust_damage_type", 3829, Parameter.ItemIdentifier),
                new Operator("item_set_swing_damage", 3830, Parameter.ItemIdentifier),
                new Operator("item_set_swing_damage_type", 3831, Parameter.ItemIdentifier),
                new Operator("item_set_head_armor", 3832, Parameter.ItemIdentifier),
                new Operator("item_set_body_armor", 3833, Parameter.ItemIdentifier),
                new Operator("item_set_leg_armor", 3834, Parameter.ItemIdentifier),
                new Operator("item_set_speed_rating", 3835, Parameter.ItemIdentifier),
                new Operator("item_set_missile_speed", 3836, Parameter.ItemIdentifier),
                new Operator("party_stack_get_experience", 3900, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_stack_get_num_upgradeable", 3901, Parameter.None, Parameter.PartyIdentifier),
                new Operator("party_has_flag", 3902, Parameter.PartyIdentifier, Parameter.PartyFlags),
                new Operator("party_heal_members", 3903, Parameter.PartyIdentifier, Parameter.TroopIdentifier),
                new Operator("position_rotate_z_floating", 4100, Parameter.Position),
                new Operator("position_get_vector_to_position", 4101, Parameter.None, Parameter.Position, Parameter.Position, Parameter.Position),
                new Operator("position_align_to_ground", 4102, Parameter.Position),
                new Operator("options_get_battle_size", 4300),
                new Operator("options_set_battle_size", 4301),
                new Operator("options_get_verbose_casualties", 4302),
                new Operator("options_set_verbose_casualties", 4303),
                new Operator("options_get_cheat_mode", 4304),
                new Operator("options_set_cheat_mode", 4305),
                new Operator("options_get_realistic_headshots", 4306),
                new Operator("options_set_realistic_headshots", 4307),
                new Operator("fld", 4400, Parameter.FloatRegister),
                new Operator("fld_str", 4401, Parameter.FloatRegister, Parameter.String),
                new Operator("fld_pos_x", 4402, Parameter.FloatRegister, Parameter.Position),
                new Operator("fld_pos_y", 4403, Parameter.FloatRegister, Parameter.Position),
                new Operator("fld_pos_z", 4404, Parameter.FloatRegister, Parameter.Position),
                new Operator("fst", 4405, Parameter.None, Parameter.FloatRegister),
                new Operator("fcpy", 4406, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("feq", 4407, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fgt", 4408, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("flt", 4409, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fge", 4410, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fle", 4411, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsub", 4412, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmul", 4413, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fdiv", 4414, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmin", 4415, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmax", 4416, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fclamp", 4417, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsqrt", 4418, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fabs", 4419, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fceil", 4420, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ffloor", 4421, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fexp", 4422, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fpow", 4423, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fln", 4424, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("flog", 4425, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fmod", 4426, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsin", 4427, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fcos", 4428, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ftan", 4429, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fsinh", 4430, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fcosh", 4431, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("ftanh", 4432, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fasin", 4433, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("facos", 4434, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fatan", 4435, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("fatan2", 4436, Parameter.FloatRegister, Parameter.FloatRegister, Parameter.FloatRegister),
                new Operator("feval", 4437, Parameter.String),
                new Operator("scene_set_flags", 4500),
                new Operator("scene_set_water_level", 4501),
                new Operator("scene_set_bounds", 4502),
                new Operator("scene_set_outer_terrain", 4503),
                new Operator("scene_set_terrain_seed", 4504),
                new Operator("scene_set_river_seed", 4505),
                new Operator("scene_set_flora_seed", 4506),
                new Operator("scene_set_deep_water", 4507),
                new Operator("scene_set_place_river", 4508),
                new Operator("scene_set_disable_grass", 4509),
                new Operator("scene_set_valley_size", 4510),
                new Operator("scene_set_hill_height", 4511),
                new Operator("scene_set_ruggedness", 4512),
                new Operator("scene_set_vegetation", 4513),
                new Operator("scene_set_size", 4514),
                new Operator("scene_set_region_type", 4515),
                new Operator("scene_set_region_detail", 4516),
                new Operator("edit_mode_in_edit_objects_mode", 4600),
                new Operator("edit_mode_get_num_selected_prop_instances", 4601),
                new Operator("edit_mode_get_selected_prop_instance", 4602),
                new Operator("edit_mode_select_prop_instance", 4603, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_deselect_prop_instance", 4604, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_get_highlighted_prop_instance", 4605),
                new Operator("edit_mode_set_highlighted_prop_instance", 4606, Parameter.ScenePropIdentifier),
                new Operator("edit_mode_set_enabled", 4607),
                new Operator("set_shader_param_int", 4700),
                new Operator("set_shader_param_float", 4701),
                new Operator("set_shader_param_vector", 4702, Parameter.None, Parameter.Position),
                new Operator("set_shader_param_matrix", 4703, Parameter.None, Parameter.Position),
                new Operator("update_material", 4704),
                new Operator("menu_create_new", 4800, Parameter.None, Parameter.None, Parameter.None, Parameter.MenuFlags),
                new Operator("menu_add_item", 4801),
                new Operator("menu_clear_items", 4802),
                new Operator("menu_clear_generated", 4803),
                new Operator("overlay_get_val", 4900),
                new Operator("presentation_activate", 4901),
            };
        }
    }
}
